### ISSUE TITLE
Move this repo from okfn to frictionlessdata.io as ideas tracker (and split out codebase)

### ISSUE THREAD

**Issue by rgrp** [frictionlessdata/project#206]
okfn/data.okfn.org => frictionlessdata/ideas

## General Overview

* [x]  sort out any outstanding pull requests etc whilst at data.okfn.org
* [x] move this repo to frictionlessdata/ideas
* [x] push a copy of the repos code to okfn/data.okfn.org-new (NOT to data.okfn.org as we want redirects to work ...)
* [x] strip content from here (push force a clean repo on master
* [x] Create a nice README

Migrating content

* [x] create frictionlessdata/frictionlessdata.io for the new website
* [x] main site as jekyll repo there - move all static content here (this is what this repo will become)
* [x] setup dns for frictionlessdata.io <del>datapackages.org</del> etc
* [x] implement redirects in DNS for relevant parts of data.okfn.org to frictionlessdata.io
 * Redirect data.okfn.org/doc/* (either en masse to fd.io/guides/ or individual pages)
 * Redirect data.okfn.org/standards/ fd.io/data-packages/
 * Redirect data.okfn.org/vision/ -> fd.io

Migrating tools: separate issue #261

Migrating catalog - seaprate issue ...
* [ ] catalog i.e. `/data/` => ??

**Comment by rgrp** [comment]
@danfowler if you are working on this could you update here what the plan is exactly so it can be briefly discussed. Also any updates on timeline.

/cc @pwalsh @jobarrat

**Comment by danfowler** [comment]
@rgrp 

1. I have redeployed a [branch](https://github.com/okfn/data.okfn.org/tree/datapackages.org) of this codebase to [heroku](http://datapackages.herokuapp.com/).
2. [datapackages.org](http://datapackages.org/) now points there
3. I will go through this site and make tweaks to ensure some consistency, fix links, etc.
4. I will start planning out the new content this week in advance of the design work

**Comment by rgrp** [comment]
@danfowler any thoughts on the process i had originally outlined. Also worth us speccing out what exactly will go and what will stay.

I imagine specifically that datapackages.org is jekyll / static only (I would highly recommend this to avoid e.g. site falling over if heroku crashes which has happened). As such, we want a migration path for various chunks of the services (maybe some stuff stays on data.okfn.org etc)

**Comment by danfowler** [comment]
@rgrp I think, for now, we have one url we can start pointing people to, datapackages.org, without spending much time at all.

With Jo and @pwalsh, we can start the process now of deciding what the new site will look like.  I'm pretty inclined to have static content hosted on GitHub Pages, limiting our reliance on an actual server running somewhere, but I think we wanted a quick fix here.

I've take /tools/ and /data/ away, and I think there's some basic refactoring of the content to be done.  what else do you think should go?

**Comment by rgrp** [comment]
@danfowler I want to note some points from chat the other day (**in progress - tbc**):

* datapackages.org should be static only and run off jekyll
* I **strongly** recommend a 1-2 approach - migrate content as is, then refactor.

Lastly: I think we should distinguish refactoring and moving this repo from the question of the site work. I need to explain this in a bit more detail ...

**Comment by danfowler** [comment]
@rgrp Now that we have https://github.com/frictionlessdata/frictionlessdata.io I'd like to move this repository to the frictionlessdata organization and rename it to "ideas" and we can keep updating with user stories.  I'll close out the website-specific issues on this repo and clear out the content.  

We can then move forward on publishing as frictionlessdata.io if you're happy with it.

**Comment by rgrp** [comment]
@danfowler so we need a bit of a plan to proper split out the different bits in this repo. Can you plan out here step by step what you plan to do so we can check it.

For example, we need to work out what still powers data.okfn.org, whether we split out the core "dataportal" code to a repo somewhere (some people seem to like that etc etc ...)

**Comment by rgrp** [comment]
OK, i've updated issue description with new, clear plan.

**Comment by rgrp** [comment]
@roll we are generally using Milestones rather than "Status" tags for indicating stuff like "Backlog"

**Comment by roll** [comment]
@rgrp I was experimenting with waffle.io based on OpenSpending (@akariv) experience. So it has been added by system when I've moved it to `Backlog` column.

https://waffle.io/frictionlessdata/ideas

Couldn't be it useful to manage this ideas?

To revert I just need to delete `Status: Backlog` label.

**Comment by rgrp** [comment]
@danfowler / @pwalsh could we look at doing the redirects listed above. I think this is a high priority as currently quite a bit of confusion ...

**Comment by danfowler** [comment]
Redirects now implemented:

https://github.com/okfn/data.okfn.org-new/commit/9d74771533f7734054dc496273bcd372fa702f28

**Comment by rgrp** [comment]
@danfowler i would *definitely* have done this in dnsmadeeasy *not* in the codebase. That way these would exist even if we move the app or take it down. Can you look at doing this in dnsmadeeasy.

Sorry if this wasn't obvious - when i mentioned in the channel i thought i'd indicated dnsmadeeasy.

/cc @pwalsh

**Comment by pwalsh** [comment]
oops. definitely something to do in DNS.

**Comment by danfowler** [comment]
New website: http://frictionlessdata.io/
Redirects implemented from old website: http://data.okfn.org
Project tracker in place: https://github.com/frictionlessdata/project
