### ISSUE TITLE
[meta] Diagram Ideas - Library Architecture, Spec Relationships etc

### ISSUE THREAD

**Issue by rgrp** [frictionlessdata/project#235]
* [ ] Data management pipeline and relationship to Frictionless Data tooling
* [ ] User story overview and relation to components
* [ ] Data Package Tool Stack

## High level user story + components view

https://docs.google.com/drawings/d/1uZhzgc43j8tQuN3MD5IoRdKUT192fvjDefNq85HtSU4/edit

<img src="https://docs.google.com/drawings/d/1uZhzgc43j8tQuN3MD5IoRdKUT192fvjDefNq85HtSU4/pub?w=648&h=361" />

## Data Package Tool Stack

See: https://discuss.okfn.org/t/data-package-libraries-overview/957

<img src="https://docs.google.com/drawings/d/1F5P5vjMe0woqLuHvBHj6Gm_gHwaqTRkJsFliu2kuq14/pub?w=1104&h=752" />

## Frictionless Data Roadmap

https://docs.google.com/drawings/d/1td7wmG54wbxCpS7kb5clPLyqESwHHTBvuxlIIRd-x5k/edit

<img src="https://docs.google.com/drawings/d/1td7wmG54wbxCpS7kb5clPLyqESwHHTBvuxlIIRd-x5k/pub?w=942&h=708" />

## Data Package "Specs"

https://docs.google.com/drawings/d/1SZxJ00WEp3iK5fqljc-yumalRePmwdaaH98_8uJYlbs/edit

<img src="https://docs.google.com/drawings/d/1SZxJ00WEp3iK5fqljc-yumalRePmwdaaH98_8uJYlbs/pub?w=358&h=330" />

## Data Packages and Ecosystem (old)

https://docs.google.com/drawings/d/1W0s91bQGS-bmGOLm519mMq9zDJvRhP71pwuJtkflRws/edit

<img src="https://docs.google.com/drawings/d/1W0s91bQGS-bmGOLm519mMq9zDJvRhP71pwuJtkflRws/pub?w=896&h=660" />

---

# Ideas from Elsewhere

## "Lego bricks"

For describing how specs or tools fit together e.g.

```
                Tabular Data Package
    |                                   |
---------   Data Descriptor ---------   |
Data Package | JSON Table Schema | CSV
```

![image](https://cloud.githubusercontent.com/assets/180658/14912539/e6aff6a6-0df4-11e6-8201-0db5e3c24a80.png)

*From: https://coreos.com/*

**Comment by danfowler** [comment]
This issue was moved to frictionlessdata/frictionlessdata.io#44
