### ISSUE TITLE
Review and actualize general project repository

### ISSUE THREAD

**Issue by roll** [frictionlessdata/project#262]
# Overview

The Frictionless Data general project repository - https://github.com/frictionlessdata/project

# Analysis

This repository has a long history and now is in a need of a review and update. This repository is supposed to be a entry point and a tracker for all high-level issues for the project so it should be well-organized and actual.

# Tasks

- [x] actualize `README.md`
- [x] for every open issue
  - [x] move to User Stories (https://trello.com/b/MGC4RpTZ/frictionless-data-user-stories) OR
  - [x] move to the actual issue tracker OR
  - [x] ensure actuality OR
  - [x] close
- [x] remove superfluous labels like "In Progress" or "Priority (star)" already covered through Waffle

**Comment by danfowler** [comment]
README.md updated: https://github.com/frictionlessdata/project

**Comment by danfowler** [comment]
User Stories here: https://trello.com/c/vUKDXvUM/99-as-a-developer-i-want-a-jquery-plugin-for-core-data-packages-so-that-i-can-use-it-to-apply-to-a-form-control-that-uses-a-core-da

I deleted the "user-story" label to make it clear that we are not tracking them here.

**Comment by roll** [comment]
:clap:
