### ISSUE TITLE
Trigger testsuite-py from all underlying libraries

### ISSUE THREAD

**Issue by roll** [frictionlessdata/project#263]
# Overview

We have https://github.com/frictionlessdata/testsuite-py repository to run integration tests. We need automatically run this tests after any change in any master branch of underlying libraries.

# Analysis

The pilot was successfully implemented for `tabulator-py` - https://github.com/frictionlessdata/tabulator-py (see `.travis.yml` and `scripts`).

# Tasks

-  [ ] tabulator-py
- [ ] jsontableschema-py
- [ ] jsontableschema-bigquery-py
- [ ] jsontableschema-pandas-py
- [ ] jsontableschema-sql-py
- [ ] datapackage-py

**Comment by roll** [comment]
Even `tabulator` doesn't work correctly for now - https://travis-ci.org/frictionlessdata/testsuite-py/builds

**Comment by roll** [comment]
will be covered at https://github.com/frictionlessdata/testsuite-py/issues/3
