### ISSUE TITLE
Encapsulate all tabular read/write operations into tabulator

### ISSUE THREAD

**Issue by roll** [frictionlessdata/project#266]
# Overview

Implementation of reading and writing tabular data is a error prone process. Especially writing in Python. It could be encapsulated to base library and re-used in many places (now almost the whole stack writes csv manually).

# Tasks

- [ ] ensure all readings thru tabulator
- [ ] https://github.com/frictionlessdata/tabulator-py/issues/36
- [ ] update all higher level libraries and tools for writing using tabulator
- [ ] mimic this approach in other language implementations where tabulator is available

**Comment by pwalsh** [comment]
I don't see why we need this issue here, when we have this here https://github.com/frictionlessdata/tabulator-py/issues/36

**Comment by roll** [comment]
I suppose the last usage of raw csv.write will be replaced here - https://github.com/frictionlessdata/datapackage-py/issues/15. So closing the meta issue.
