### ISSUE TITLE
Finalize a few critical to implementations changes to specs

### ISSUE THREAD

**Issue by roll** [frictionlessdata/project#267]
# Overview

I've reviewed `specs` issues and found a few critical things to our starting multi-language work on JTS and DP implementations. I suppose this proposals should be merged/rejected as soon as possible:

- [ ] Merging path and url - https://github.com/frictionlessdata/specs/issues/250
- [ ] Cache - https://github.com/frictionlessdata/specs/issues/243 (**added**)
- [ ] Remove 'fmt:' prefix - https://github.com/frictionlessdata/specs/issues/260
- [x] Enum constraint exact matching - https://github.com/frictionlessdata/specs/issues/221
- [x] Multiple urls for resource - https://github.com/frictionlessdata/specs/issues/247

**Comment by pwalsh** [comment]
@rgrp see above.

**Comment by rgrp** [comment]
Ack and note existing issue https://github.com/frictionlessdata/project/issues/241 - something of a duplicate of this one or vice-versa.

@pwalsh the real blocker here is a proper conversation with you to resolve these one way or the other.

**Comment by roll** [comment]
Closing it because now we track `specs` repository on the FD board so this issue is just a duplicate of:
- Merging path and url - frictionlessdata/specs#250
- Cache - frictionlessdata/specs#243 (added)
- Remove 'fmt:' prefix - frictionlessdata/specs#260
