### ISSUE TITLE
Setup linting for all python libraries

### ISSUE THREAD

**Issue by roll** [frictionlessdata/project#269]
# Overview

For now it disabled because of pylint->pylama migration.

# Tasks

-  [x] tabulator-py
- [ ] jsontableschema-py
- [x] jsontableschema-bigquery-py
- [x] jsontableschema-pandas-py
- [x] jsontableschema-sql-py
- [ ] datapackage-py

**Comment by roll** [comment]
FIXED/MOVED
https://github.com/frictionlessdata/datapackage-py/issues/36
https://github.com/frictionlessdata/jsontableschema-py/issues/79
