### ISSUE TITLE
Data Quality Dashboard release

### ISSUE THREAD

**Issue by pwalsh** [frictionlessdata/project#278]
# Description

Requires #311
# Tasks
- [ ] blog post
  - [ ] showcase the various instances we have: spend, some ckans, etc.
  - [ ] go into detail on different aspects
  - [ ] types of quality assessment, why
- [ ] supporting materials for pilots
- [ ] Labs mailing list
- [ ] Labs discussion lists
- [ ] Network tech leads
- [ ] Social media channels
