### ISSUE TITLE
International Data Week Materials

### ISSUE THREAD

**Issue by danfowler** [frictionlessdata/project#290]
- [x] SciDataCon: Towards a Frictionless Data Future: https://github.com/frictionlessdata/frictionlessdata.io/issues/67
- [ ] RDA: Frictionless Data (HDF Session): https://github.com/frictionlessdata/frictionlessdata.io/issues/68
- [x] Frictionless Data One Pager: https://github.com/frictionlessdata/frictionlessdata.io/issues/66

**Comment by danfowler** [comment]
@jobarratt it occurs to me that it would be good to have one pager I wrote on hand to distribute.  Do you think it needs any edits/polishing?
