### ISSUE TITLE
services.frictionlessdata.io

### ISSUE THREAD

**Issue by pwalsh** [frictionlessdata/project#311]
# Description

We want to have commercial offerings for Frictionless Data. This comes from two angles:
- We think we have some products that are commercially viable, and basic offerings, lean-startup style, will position us to be able to do basic product/market validation (on top of the extensive work we are doing towards that anyway with piloting and so forth)
- We want to experiment with this as part of a sustainability strategy for Frictionless Data in general
# Tasks

Initial bootstrap with a vanilla bootstrap theme on jekyll. Goal is to get content architecture and simple UX in place.
- [ ] Home page
  - [ ] What is it
  - [ ] Why
  - [ ] Products
    - [ ] Data Quality Dashboard
    - [ ] GoodTables.io
  - [ ] Services
    - [ ] Custom dashboards
    - [ ] Custom specifications
    - [ ] Custom data processing
- [ ] Product page for each product/service
  - [ ] Stripe integration

After this we can do a minimal design.

**Comment by tfmorris** [comment]
Are these OK*[1] commercial offerings or offerings from another organizational entity? Who?

[1]no longer trying to keep track of the varying names or acronyms

**Comment by pwalsh** [comment]
@tfmorris "We" refers to the team at OKI working on Frictionless Data, yes.

**Comment by pwalsh** [comment]
closing as low priority
