### ISSUE TITLE
Goodtables Lib Blog post

### ISSUE THREAD

**Issue by jobarratt** [frictionlessdata/project#325]
# Tasks
- [x] Read http://okfnlabs.org/blog/2015/02/20/introducing-goodtables.html 
- [x] Install Jupyter Notebooks using advanced method https://jupyter.readthedocs.io/en/latest/install.html
- [x] Install good tables on CLI https://github.com/frictionlessdata/goodtables-py and http://goodtables.readthedocs.io/en/latest/ 
- [x] For the blogpost
  - [x] Understand  and summarise how the GT Lib works
  - [x] Select two - three user stories to work with from https://trello.com/b/MGC4RpTZ/frictionless-data-user-stories 
  - [x] Identify what’s been fixed since blogpost 1
  - [x] Outline lessons learned
  - [x] show several examples of gt in action using the selected user stories
