### ISSUE TITLE
Update all Frictionless Data specs to V1

### ISSUE THREAD

**Issue by pwalsh** [frictionlessdata/project#337]
# Description

v1 of `datapackage.json` (Base and Tabular), `dataresource.json` (Base and Tabular), and `tableschema.json`. Signed, sealed and delivered.

# Tasks

- [x] Data Resource and Data Tabular Resource specifications
- [x] Submit all mimetypes
- [x] Close all v1 issues and merge to v1 of each specification
- [x] Refactor the way a spec is written to reduce duplication and different wording that leads to ambiguity

**Comment by pwalsh** [comment]
DONE.
