### ISSUE TITLE
Announce Frictionless Data specifications v1

### ISSUE THREAD

**Issue by pwalsh** [frictionlessdata/project#341]
# Description

Requires https://github.com/frictionlessdata/project/issues/337

The v1 release of the Frictionless Data specifications is a big deal. We need to tell the world

# Tasks

- [x] Submit first draft to colleagues
  - [x] History/context
  - [x] Current piloting and development
  - [x] goals of v1
  - [x] what is new/has changed
  - [x] which libs have implemented v1
  - [x] The registry
    - [x] Draw from: https://github.com/frictionlessdata/specs/issues/87#issuecomment-158302576
    - [x] Point to: http://schemas.frictionlessdata.io/registry.csv
    - [x] What is JSON Schema?
    - [x] Motivation
    - [x] How to Contribute
   - [x] Update registry URLs: https://github.com/frictionlessdata/schemas/issues/58
- [ ] Iterate on final draft
- [ ] Publication on Labs and main OKFN blogs
- [ ] Alert @danfowler for social media etc.

**Comment by pwalsh** [comment]
https://hackmd.io/KwUzE5wIwRgWgGYENzDgFmAgzHKA2fJOABmHwGMATEmK8GIoA===

**Comment by pwalsh** [comment]
Now assigning to @danfowler to finish.

**Comment by pwalsh** [comment]
I've also invited @rufuspollock to edit if he likes.

**Comment by roll** [comment]
DONE

**Comment by pwalsh** [comment]
done
