### ISSUE TITLE
Implement Frictionless Data specs v1 in core libs

### ISSUE THREAD

**Issue by pwalsh** [frictionlessdata/project#343]
# Description

No good having a spec with no implementation! We need to ensure coverage in the core libraries.

# Tasks

- [ ] Implement all v1 changes in Python libs
- [ ] Implement all v1 changes in JavaScript libs
- [ ] Open a v1 issue on each partner library, with a clear task list of what needs to be changed for v1 update

**Comment by pwalsh** [comment]
closed for https://github.com/frictionlessdata/stack/issues/3
