### ISSUE TITLE
Bootstrap process for additional implementations

### ISSUE THREAD

**Issue by pwalsh** [frictionlessdata/project#344]
# Description

We have some funds - and drive! - to do implementations of the FD specs in programming languages we are not familiar with. This is a great opportunity to both introduce Frictionless Data to new communities, and to get critical feedback from new implementors.

# Tasks

- [x] Select a few core, strategic languages that we'd like to see libraries implementing the specs in
- [x] Build a larger list of nice to have implementations
- [x] Produce excellent implementation documentation ( with @roll ), based on:
  - [x]  https://gist.github.com/pwalsh/62d967d11369b38bd5d05bbc519fe1ba 
  - [x] https://github.com/frictionlessdata/project/issues/288 and 
  - [x] https://github.com/frictionlessdata/project/issues/289
- [x] Build a process to reach out to developers in these various languages. First via connections, then network, then public places for each language, and so on

**Comment by pwalsh** [comment]
I think I'm done with the implementation docs. @roll your comments/edits welcome:

https://gist.github.com/pwalsh/62d967d11369b38bd5d05bbc519fe1ba

**Comment by pwalsh** [comment]
@jobarratt done.

**Comment by roll** [comment]
@pwalsh 
looks good :+1: 
Some links outdated - like model instead of schema TS model. Also not linked datapackage-js in examples.

Also a few thoughts:
- not specified that descriptor could be remote/local/native
- it's optional but data package identifier could be mentioned

**Comment by roll** [comment]
Where we're going to host it? Stack reference is a live document for now. We could have it as `stack` repo file (or 2 files separating stack ref)

**Comment by pwalsh** [comment]
I don't want another repo: either with the specs (implementations section) or with the main site. WDYT?

**Comment by roll** [comment]
@pwalsh 
are you sure you need to have stack reference inlined instead of just linked?

**Comment by roll** [comment]
I think it will be much flexible if I will put all low-level working information (stack reference, vocabulary etc) in e.g. `stack` repo README.md and in high-level documents you'll be liking it if needed.

**Comment by pwalsh** [comment]
I can remove the signatures of classes/functions, if that is what you mean?
