### ISSUE TITLE
GoodTables.io MVP Scope

### ISSUE THREAD

**Issue by pwalsh** [frictionlessdata/project#345]
# Description

We want to launch GoodTables.io as a publicly accessible service in February 2017.

# Tasks

-  [ ] Start from the original product requirements and user stories, and produce an updated PRD that describes the public, launchable MVP
- [ ] Fill out the "Product Vision" document for GoodTables.io
- [ ] Work with @smth on a first iteration of UX
- [ ] Add issues to GoodTables.io backlog as user stories, to capture any undeclared requirements for the MVP
