### ISSUE TITLE
Fix bugs on new specs website

### ISSUE THREAD

**Issue by pwalsh** [frictionlessdata/project#347]
# Description

We shipped v1 with a major change to how specs are produced and displayed. There are some bugs that need to be fixed so that the specs display the correct information, and some enhancements to make so that working with the new codebase is clearer.

# Tasks

- [x] Update the README with better instructions for contributing, and running the site
- [x] Make `sources/dictionary.json` `sources/dictionary.yml`, and also tidy up the examples snippets as using YAML frees us up there
- [x] don't commit the generated database for the specs
- [x] dereference is for FAQs
- [x] Patterns fix (separate after merge!)
- [x] Make the links to the JSON Schemas that validate the specs much more prominent as part of each spec page
- [x] Make links to reference implementations of each spec prominent on each spec page
- [x] http://specs.frictionlessdata.io/data-resource/ examples still use `path` instead of `uri`
- [x] Fix all old redirects. Example: `/json-table-schema/ not redirecting to /table-schema/`, `/data-packages/ not redirecting to /data-package/`
- [x] Some code highlighting broken ({% highlight %} tags can be replaced with ```): http://specs.frictionlessdata.io/data-package-identifier/#identifier-object-structure
- [x] update example profile ids to reflect the new names of these ids (e.g. 'fiscal' -> 'fiscal-data-package'): http://specs.frictionlessdata.io/data-resource/#optional-properties
- [x] render unrendered html (e.g. `<code>data</code>`): http://specs.frictionlessdata.io/tabular-data-resource/#example-2
- [x] "Lacking a single piece of actual data would make this Data Package of doubtful use.":  Data Packages can contain inline data, so a lone `datapackage.json` could contain multitudes :) http://specs.frictionlessdata.io/data-package/#example-1
- [x] Link to all specs on front page grouped
- [x] render unrendered Markdown (e.g. `backticks` and **double asterisks**) when rendering schemas
- [x] left indentation and general wrapping of code sections is weird
- [x] Fix rendering logic for nested objects (noticeably problematic on Table Schema)

**Comment by danfowler** [comment]
- [ ] /json-table-schema/ not redirecting to /table-schema/

**Comment by rufuspollock** [comment]
@danfowler could you PR your typos and style branch right now - let's get these fixes straight into master so we move quickly and don't duplicate each others work 😄

**Comment by danfowler** [comment]
@rufuspollock sure

**Comment by pwalsh** [comment]
- yaml dictionary
- don't commit the generated database for the specs

**Comment by pwalsh** [comment]
- [ ] dereference is for FAQs
- [ ] Patterns fix (separate after merge!)
- [ ] Link to all specs on front page grouped

**Comment by rufuspollock** [comment]
@pwalsh i fill a little blocked on doing much on the specs due to the current restructuring change -- I guess i have to install lektor, i have to open a json file to edit the specs (?):

```
If you want to update the specifications, start in `sources/dictionary.json`.
```

Is there any way to get nice old markdown files to edit ;-) ?

**Comment by pwalsh** [comment]
not really. it will improve once I change dictionary.json to a yaml file though.

**Comment by rufuspollock** [comment]
@pwalsh there are some major bugs atm e.g. type list on JSON Schema now has no formats afaict ...

Also left indentation and general wrapping of code sections seems weird on that entire spec seems weird.

I'm really struggling to work out how to fix this stuff with the new dictionary.json.

This is somewhat **urgent** I'd suggest -- having a half baked site out there is not so great [1]. I'd love to dive in but i'm genuinely struggling to see how this gets built together and where e.g. the formats stuff has gone :wink:

[1]: I noticed this latest item when responding to a query on the FD chat channel

**Comment by danfowler** [comment]
From @roll : http://specs.frictionlessdata.io/data-resource/ examples still use `path` instead of `uri`

**Comment by pwalsh** [comment]
(I've edited the above and consolidated everything into a single, clear list in the first post)

**Comment by rufuspollock** [comment]
@pwalsh could we also move this to the specs repo -- it is the natural place for it ...
