### ISSUE TITLE
[epic] Improve Frictionless Data website [Jan 2019 ongoing]

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/project#373]
Improving the Frictionless Data website and overall "developer experience" for the project as a whole.

## Tasks

* [ ] Get list of properties (i.e. something that is on web and gets traffic) and associated info including traffic stats #376 

---

### General UX

* [ ] No way to link to sections of specs (no anchor option - there was in the old version!). This is really important. I constantly want to drop a link to someone and having to paste a title of a section is annoying.
* [ ] Magical Table of contents on left is very annoying (see specs section as an example)
* [ ] Top of page navbar does not have the main links for users (stuff hidden in an accordion)
* [ ] No "edit this page" links (at least on pages like patterns)
* [ ] can we get a proper nave menu not a drop-down one. I want to see at a glance the key things i can find or do.

### Theme

* [ ] Black theme has a poor feel IMO. Old theme was quite nice and had an "open", "breathing" sense to it (it even got copied!)
* [ ] Dubious about the logo
* [ ] Font is tough to read (very small) and ugly - old specs site was more readable

### Front page

* [ ] Tagline is very weak (compared to before)
* [ ] Main text is about watching the video rather than what we are about
* [ ] Main call to action is "play" video button which could just be part of video!
  * [ ] video does not show up on mobile
* [ ] remove the read more / read less button about the vision - just show it all so that i don’t have to click on something to read it all and it is all visible at first glance (when i see read more i think i’m going to go to a different page).

### Misc Content

* Get vision and principles back on FD.io
* Look up frictionless components diagram from old data.okfn.org

### Tools Page

* Mosaic layout is for images not info of tools
* What do i want to do know?
  * Core tools / libs by language and their status and compliance
  * Sample table layout below ... 

| _        | Python | Javascript |
| -------- | -------- | -------- |
| Table Schema     | ✓ (v1.0) Link    | ✓   |
| Data Package     | ✓ (v1.0) Link  | |

---

### Main site: frictionlessdata.io

https://web.archive.org/web/20170927073213/https://frictionlessdata.io/

* Very simple, very clear front page (could probably have had a bit more on it)
* Tagline: Lightweight standards and tooling to make it effortless to get, share, and validate data.
  * Compare with today: "Processing, publication, access, insight. The future of data is frictionless." which sounds weird, unclear and like marketing BS ...
* Design is clean and light ... 

![image](https://user-images.githubusercontent.com/180658/52308078-4a4d7680-2994-11e9-94fe-37ebd8ae65f4.png)

New site:

![image](https://user-images.githubusercontent.com/180658/53193675-7f4eff80-3609-11e9-9cc2-4247e9980e57.png)

### Specs: specs.frictionlessdata.io

https://web.archive.org/web/20171029113319/http://specs.frictionlessdata.io/

* Plain, simple, does what it says on the tin ...
* Links to Pre v1 (useful to some)
* Clear nav links
* Clear links to specs on left for ease of navigation

![image](https://user-images.githubusercontent.com/180658/52308017-25590380-2994-11e9-9e9b-0a1fd6ffadc5.png)

### Tools

https://frictionlessdata.io/software/ [cached screengrad](https://user-images.githubusercontent.com/180658/52308295-d9f32500-2994-11e9-8a5e-0dc62de6cd08.png)

Old site: https://web.archive.org/web/20171012103437/http://frictionlessdata.io/tools/

* Current site uses an tiling setup for images for a listing of code libraries!!! Terrible UX ...
* Also now called software rather than tools (but includes things that aren't software e.g. online services ...)

**Comment by rufuspollock** [comment]
DUPLICATE. This is now merged into a major website improvement effort covered in https://github.com/frictionlessdata/project/projects/2
