### ISSUE TITLE
List of FD properties and associated info e.g. traffic

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/project#376]
Get list of properties (i.e. something that is on web and gets traffic) and associated info including traffic stats.

Why? For purposes of improving website etc #373 we want to know what we have and what is being used ...

## Acceptance criteria

* [x] Spreadsheet list of main properties other than github repos ...  (plus key columns)
https://github.com/frictionlessdata/project/issues/376#issuecomment-565317015
* [x] CSV of all the repos with their traffic that we could merge in (separate for now as we automate this part probably). --> https://github.com/monikappv/frictionless-data-repos
@monikappv 
   * Bonus for having:
     * url of repo
     * title / description
     * link from repo
   * Bonus for making this a data package
https://github.com/frictionlessdata/project/issues/376#issuecomment-564970945

## Tasks

* [x] Get list of 88 repos
* [x] Get their traffic -- see below on how
  * [x] do for one
  * [x] do for all

### How to get github repo traffic via API

```
curl -u {your-name} https://api.github.com/repos/frictionlessdata/specs/traffic/views
```

![image](https://user-images.githubusercontent.com/180658/70393108-370d9c00-19e7-11ea-96ea-bb1f001084da.png)
### The data package

https://github.com/monikappv/frictionless-data-repos

### The script in gist

https://gist.github.com/monikappv/9cbdd0de851c8ed7261a57475eac68e6

**Comment by monikappv** [comment]
Using this API given above (https://api.github.com/repos/frictionlessdata/specs/traffic/views), i got the error message **"Must have push access to repository"**.

So I created a token and attached it to the API-link, which gave me access to the data. I get the views information as a JSON file containing the **"count" and "unique" numbers** for the last 14 days + "total count" and "total unique" as shown below:

![api_views](https://user-images.githubusercontent.com/56799741/70629765-2b161a00-1c33-11ea-9043-7fc94acf843c.png)

I extracted this information, since I assumed this is what's needed and put it in one csv file. I did the same for the number of clones (since I thought I heard it might also be cool having)

In order to complete another part of the tasks (list of all repos + url, description etc), I used this API:
https://api.github.com/orgs/frictionlessdata/repos 
I extracted the values I assumed might be needed - repo title, url, description, forks, open issues, views. However, the views number does not overlap with the number of views on the traffic page of the repo in github - https://github.com/frictionlessdata/specs/graphs/traffic.

Endresult was 3 CSV files, instead of 1... 
1. list of all repos with description, url, forks number, views number, open issues number
2. list with number of clones for one repo (specs) for the last 4 days 
3. list with number of views for one repo (specs) for the last 14 days

**Comment by monikappv** [comment]
I created a branch features\list_repo fulfilling all requirements.. going to create a merge request tomorrow.

**Comment by monikappv** [comment]
CSV file is created and integrated in the [FD spreadsheet](https://docs.google.com/spreadsheets/d/1qByu4qw56hFUdJIY5IOC7d8TQBud-k31J6720hg1h2w/edit#gid=55598434). 
Data Package is available here --> https://github.com/monikappv/frictionless-data-repos

Note: 
* watchers numbers are not accurate (also in the source) and overlap with the stars numbers

**Comment by dipeshkhadkaa** [comment]
* I have added a website and links related to frictionless data in the [FD spreadsheet](https://docs.google.com/spreadsheets/d/1qByu4qw56hFUdJIY5IOC7d8TQBud-k31J6720hg1h2w/edit#gid=55598434). 
* As there were many articles related to this but from other sources. Mostly choose apps, websites, and media mainly. And couldn't fill the whole columns because of the lack of info like GitHub. 
* I couldn't check the checkbox of the task as done in "acceptance criteria" above.

**Comment by cabral** [comment]
@rufuspollock 

I'm moving this issue to the DONE column, so you can review it and if is OK, you can close it.

**Comment by rufuspollock** [comment]
@cabral how is this done if we don't have traffic stats for the main website yet?

**Comment by cabral** [comment]
Moving back to TODO. 

Reason: Need to add traffic stats (main site and goodtables)

**Comment by dipeshkhadkaa** [comment]
In the [sheet](https://docs.google.com/spreadsheets/d/1qByu4qw56hFUdJIY5IOC7d8TQBud-k31J6720hg1h2w/edit#gid=55598434) we can generally take the traffic of three domains i.e 
* [fd.io](frictionlessdata.io), 
* [good tables](goodtables.io) & 
* [datahub](datahub.io) which I generally did from [hypestat](hypestat.com) and [similarweb](similarweb.com). 
These tools are free and don't need to get signup (extensions also can be used for similar web) and the traffic they provide is updated in the sheets as well as some info has been added as the notes in the sheet.

**Comment by rufuspollock** [comment]
@dipeshkhadkaa why are we using hypestat - we have analytics for this directly.

**Comment by dipeshkhadkaa** [comment]
Well, I actually didn't know that..
So I assumed it and research to look at some of the sites that could actually give us the traffic without being an owner.

**Comment by rufuspollock** [comment]
@dipeshkhadkaa did you look at the website?  There is a large datopian logo on it - might give a hint that it was associated with us 😉

**Comment by rufuspollock** [comment]
FIXED. Still waiting on goodtables.io but not a biggie

/cc @lwinfree let us know when goodtable analytics access is done

**Comment by monikappv** [comment]
@rufuspollock I have already received an e-mail that I have access to goodtables (probably 10 days ago) and have also added the views + unique views numbers to the spreadsheet. Haven't you also received access to goodtable analytics?

**Comment by lwinfree** [comment]
@rufuspollock have you checked your goodtables analytics access? Let me know if you still can't get in and I can look into it more - you should have been able to access it.
