### ISSUE TITLE
What are people's current conceptions and experience now?

### ISSUE THREAD

**Issue by monikappv** [frictionlessdata/project#378]
When I'm planning the improvement of my website, I want to know what are people's current conceptions and experience with it, so that I can find out what works, what doesn't work and what needs to be improved. 

Expected outcome: we can learn what needs to be changed in Frictionless Data in general, according to the community. 

## Acceptance criteria

* [x] spreadsheet list of people we interviewed/could interview + their feedback ordered by priority https://docs.google.com/spreadsheets/d/1qByu4qw56hFUdJIY5IOC7d8TQBud-k31J6720hg1h2w/edit#gid=1849272767
* [x] Collate resposes and summarize from survey in #396 - Create a document with what we learned from the survey responses. - https://docs.google.com/document/d/1WHaD5c3nAMbE9A5Xy-452Gq5z-EyHj9Zs7jV4XycLmc/edit#
In general:
    * Who are the respondents?
    * What they do?
    * How they want us to improve Frictionless Data?
    * What's their experience with Frictionless Data?

## Tasks

* [x] create a list of people we interviewed/could interview
* [x] prioritize based on criteria 
* [x] add their feedback 
* [x] Survey - #396 
* [x] Analyze survey

**Comment by rufuspollock** [comment]
Quite a bit done:

* We have collated a lot of existing feedback
* Rufus did a specific analysis
* Interviewed @augusto-herrmann and others

**Comment by monikappv** [comment]
FD User Survey + Interviews summary here --> https://docs.google.com/document/d/1WHaD5c3nAMbE9A5Xy-452Gq5z-EyHj9Zs7jV4XycLmc/edit#

**Comment by monikappv** [comment]
FIXED.
