### ISSUE TITLE
User survey for the site and community

### ISSUE THREAD

**Issue by monikappv** [frictionlessdata/project#379]
When I implement improvement measures on my website, I want to interview people who have used it and gather their feedback so that I can improve the quality and usability of my website based on that. 

Draft in progress here: https://docs.google.com/document/d/17OiNudAcmgsdttIftj-yNHMFjyIbm6NYtYgBaxagO8w/edit#

## Acceptance criteria

* [x] google form + link to fd.io

## Tasks

* [x] Think of good questions for a survey
* [x] Create a Google Form using them
* [x] Put link to fd.io in the Google Form

**Comment by cabral** [comment]
Form link, closed: https://docs.google.com/forms/d/1K6ztBQqE6j76dqvyk1ZLPIjheKUtj0c76uEaddCrkd0/edit

**Comment by cabral** [comment]
@monikappv Form is ready with the questions.

**Comment by rufuspollock** [comment]
@cabral @monikappv acceptance criteria don't make sense to me - what is "link to site"?

Where are the questions for review? Questions really need to be nailed here before we send out - @cabral i thought we discussed that we would draft first in google doc and *only* once "done" would we move to a form. I've commented on the draft and i think we need to do some work there before this is ready.

**Comment by monikappv** [comment]
@rufuspollock 

It did not make much sense to me either, since I don't know how you used to have it on datahub... (the initial task was "Add a user survey as banner to current site - google form plus add link to site (like we used to have on datahub.io)"). I guess it is meant that the link to fd.io should be placed somewhere in the google form....so I changed the description a little bit.

**Comment by cabral** [comment]
@rufuspollock Just checked your comments about the questions on the Doc, will continue from there. 

About "link to the site" 
Was an original piece from the issue tree - Needs definition from the P.O on "how we want to share this form doc" - will continue the discussion withing google chat.

**Comment by cabral** [comment]
Following @rufuspollock reassignment request

**Comment by Irio** [comment]
Today, I took over this task for some time to do another iteration and come up with a list of nine question. In a rough estimation, it should not take more than 3-5 minutes to answer. The draft is in the same document linked in the first comment.

**Comment by Irio** [comment]
The survey is done and ready to receive responses at https://docs.google.com/forms/d/e/1FAIpQLSdQ0U7sEVTQa0qdR0n7LI3zzimwNeIIPekaGPOwipdF1dTBEQ/viewform.
