### ISSUE TITLE
Migrating towards Frictionless Data Lib: a standard pattern for our data libraries

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/project#380]
The full RFC for this (in progress) is here:

https://github.com/frictionlessdata/project/blob/master/rfcs/0005-migrate-libraries-to-frictionless-data-lib-pattern.md

## Tasks

* [x] Stub the RFC https://github.com/frictionlessdata/project/blob/master/rfcs/0005-migrate-libraries-to-frictionless-data-lib-pattern.md
* [ ] Review existing libraries and do a gap analysis
* [ ] Short intro / guide to writing a Frictionless Data lib
* [ ] Trial for one language (e.g. python or javascript)
* [ ] Decide whether worth doing generally as recommended default pattern for libs

**Comment by augusto-herrmann** [comment]
I always for making things simpler to use. Just like, in Python, when using pandas, you can do something like this:

```python
import pandas as pd
df = pd.read_csv('https://example.com/table.csv') # get a Pandas DataFrame
```
and in the background Pandas automagically deals with things like requests, we could have something like

```python
import frictionless as fd
tables = fd.read_dataset('https://example.com/datapackage.json')
df = tables['mytable'] # get a Pandas DataFrame
```
This could be made with just a simple wrapper around `tableschema-py` and `datapackage-py`. It would be even easier to use than it already is (see [this tutorial](https://github.com/frictionlessdata/docs/blob/master/docs/tutorials/jupyter-pandas-tutorials/plotting-data-packages-with-pandas-and-plotly.ipynb)), which in turn would encourage more people to use it.

**Comment by roll** [comment]
@lwinfree 
That's a good example of why we need to improve the docs. This code is deprecated like 3 years ago and still popping out in different places:

```
>>> import datapackage

>>> data_url = 'http://data.okfn.org/data/core/country-list/datapackage.json'
>>> storage = datapackage.push_datapackage(data_url, 'pandas')

>>> storage.buckets
['data___data']

>>> type(storage['data___data'])
<class 'pandas.core.frame.DataFrame'>

>>> storage['data___data'].head()
```

**Comment by roll** [comment]
@augusto-herrmann 

The modern API is:

```python
from datapackage import Package

# Pandas
package = Package(''https://example.com/datapackage.json'')
storage = package.save(storage='pandas')
# now pandas dataframe is storage['country_codes']

# SQL
package = Package(''https://example.com/datapackage.json'')
storage = package.save(storage=sqlalchemy.create_engine('DATABASE_URL'))
# now it's in your database

# The same for:
# BigQuery
# Elasticsearch
# SPSS
# ckan-datastore
# etc
```

TBH I don't see why it's more complex than your example :smiley:  

The problem that project is by definition is really general. Consider this snippet,

```python
import frictionless as fd
tables = fd.read_dataset('https://example.com/datapackage.json')
df = tables['mytable'] # get a Pandas DataFrame
```
But why e.g. it exports the dataset to Pandas instead of SQL or not reading into memory. For Pandas user it's obvious but it's not for e.g. BigQuery user. And it's not needed if you just want to play with it in Python. So we need to add flags to this function etc. Then think about the terminology `read/dataset/etc`. The devil in the details as usual

I agree we can have something like:

```python
dfs = fd.package_to_pandas('datapackage.json')
```
But my honest opinion that proper documentation is more important

**Comment by augusto-herrmann** [comment]
@roll 
I completely agree with you, Евгени.

Having up to date documentation is essential. And even though Pandas is so popular now, it's a completely valid argument to leave the lib non opinionated and let people use and specify explicitly the tool they want to use.

Do you think cutting a step like this make sense, then?

```python
import frictionless as fd

tables = fd.read_dataset('https://example.com/datapackage.json', storage='pandas')
df = tables['mytable'] # get a Pandas DataFrame

classes = fd.read_dataset('https://example.com/datapackage.json', storage=sqlalchemy.create_engine('DATABASE_URL'))
q = session.query(classes['mytable']) # query with SQL Alchemy
```

BTW, I think it's a bit inconsistent that for Pandas we use a string `storage='pandas'` and for SQL Alchemy we pass an object as parameter. Perhaps it should be `storage=pd.DataFrame` instead?

**Comment by roll** [comment]
@augusto-herrmann 
> BTW, I think it's a bit inconsistent that for Pandas we use a string storage='pandas' and for SQL Alchemy we pass an object as parameter. Perhaps it should be storage=pd.DataFrame instead?

You're absolutely right :smiley: There is a typo:

```
# SQL
package = Package('https://example.com/datapackage.json')
storage = package.save(storage='sq', engine=sqlalchemy.create_engine('DATABASE_URL'), **opther_sql_options)
```

Regarding some umbrella library, I think it makes sense to think about what can we do using `tabulator/tableschema/datapackage/goodtables` as building blocks. We just need to think it thoroughly because another layer of functionality means another level of documentation, propagating new features  etc

**Comment by rufuspollock** [comment]
DUPLICATE. Closing this in favour of the RFC https://github.com/frictionlessdata/project/blob/master/rfcs/0005-migrate-libraries-to-frictionless-data-lib-pattern.md - let's do PRs and discussion there.

**Comment by lwinfree** [comment]
Hi @rufuspollock do you have some guidelines already created for how you want people to interact with the RFC documents? I'm worried that people might not comment/do a PR/contribute to them since it isn't as easy as writing a comment in an issue. Maybe you could write a sentence or two at the top of the RFCs telling people how to contribute? (like, please open a PR...etc etc..)

**Comment by rufuspollock** [comment]
@lwinfree first to emphasize that people can still open issues - in fact that is the best way to start. We would only move stuff to RFCs only when needed (and it is clear it is substantive, longer-term type of thing). 

I also agree on having some info on RFCs and have created #510

**Comment by lwinfree** [comment]
Awesome thanks @rufuspollock !

**Comment by rufuspollock** [comment]
FIXED. we have agreed this as part of https://github.com/frictionlessdata/project/blob/master/rfcs/0006-software-structure.md and marked https://github.com/frictionlessdata/project/blob/master/rfcs/0005-migrate-libraries-to-frictionless-data-lib-pattern.md as approved.
