### ISSUE TITLE
What is our new/refined/clarified brand?

### ISSUE THREAD

**Issue by monikappv** [frictionlessdata/project#382]
When I want to implement improvement measures on my website, I want to be clear on what is our current brand, so that I can refine and improve it.

## Acceptance criteria

* [x] Google docs with all of the below listed things 

## Tasks

* [x] Summarize in 2-3 sentences what is our core purpose (our why)?
* [x] Write briefly what do we do and how do we do it 
* [x] Create a list of differences (what's different about us..?)
* [x] Create a list of our personality / values
* [x] Create a list of potential users and their high level "jobs to be done"

**Comment by rufuspollock** [comment]
FIXED. See https://docs.google.com/document/d/1iENSKbY9ESya9yE1P52gsKDWKb2fW2U9iZZJnfJ1ucU/edit#

Of course needs (more) discussion with people (this is draft) 😄
