### ISSUE TITLE
Ecosystem research

### ISSUE THREAD

**Issue by monikappv** [frictionlessdata/project#383]
Aim would be a rough overview of the ecosystem in which FD lives and other related initiatives.

## Acceptance criteria

* [x] We have a sheet with a number of other inititatives, specs tools that are relevant (at least 10). More focused on initiatives and specs than tools (since tools is massive and more focused on related to FD as a whole)

## Tasks

* [x] do a research on who else is in the space
* [x] Create a spreadsheet with key fields and maybe some dimensions (e.g. area this is in etc)
* [ ] (?) create an ecosystem map (including alternatives, complementors, peers, other reference points)

**Comment by Irio** [comment]
I started doing this in https://docs.google.com/spreadsheets/d/1ylohGHU1TkuPg6YsWYMW2zTSeGhA9xNawQbA6ICKY8w/edit#gid=0

**Comment by rufuspollock** [comment]
FIXED. We have 14+ items including some key orgs and specs in Ecosystem Sheet https://docs.google.com/spreadsheets/d/1qByu4qw56hFUdJIY5IOC7d8TQBud-k31J6720hg1h2w/edit#gid=769659857

In addition we have more detailed mapping of more stuff in the High Level Job Stories https://docs.google.com/spreadsheets/d/1qByu4qw56hFUdJIY5IOC7d8TQBud-k31J6720hg1h2w/edit#gid=2050389930
