### ISSUE TITLE
[v2] A list of products with structure / taxonomy

### ISSUE THREAD

**Issue by monikappv** [frictionlessdata/project#384]
A list of products with structure / taxonomy (at the low level e.g. specs vs tools)

WIP here: https://docs.google.com/spreadsheets/d/1qByu4qw56hFUdJIY5IOC7d8TQBud-k31J6720hg1h2w/edit#gid=311025204

## Acceptance criteria

* [x] A list of all the products
* [x] Taxonomies / dimensions chosen
  * (Is there a primary organizing mental model for products different from this ...?)
* [x] Dimensions applied to products
* [ ] Input from other Frictionless Data contributors

## Tasks

* [x] List all the products - can start with the raw list we had https://docs.google.com/spreadsheets/d/1qByu4qw56hFUdJIY5IOC7d8TQBud-k31J6720hg1h2w/edit#gid=1252612369
  * Note you may need to treat "root/family" nodes specially e.g. the specs page as home for all specs
* [x] Identify useful dimensions (don't overdo this for now as this won't be primary route in )
* [x] Review the complete list of products
* [x] Ensure all products have their proper URLs
* [x] @monikappv - Copy current descriptions/suggested descriptions
* [x] Fill out missing purposes

**Comment by Irio** [comment]
After a couple of hours of work pairing with @monikappv, we have a list of products categorized in Purpose, Type, Parent Product, and Status.

<img width="1088" alt="Screenshot 2020-01-09 at 16 40 16" src="https://user-images.githubusercontent.com/667753/72081427-c10a9680-32fe-11ea-98b2-ccc0178e2cac.png">

**Comment by monikappv** [comment]
@lwinfree @jobarratt Let's collaborate on this! @Irio and I have been trying to get this done. The purpose is to ensure that the proposed descriptions match the intention of each of the products.

Secondarily, a thorough review on this whole "Product" sheet would be quite useful. The "Status" column is not crucial at this moment, but it would be nice to have a rough estimation.

**Comment by lwinfree** [comment]
Hey @monikappv! This is a super useful spreadsheet, and I think the new descriptions all sound good. I've Here are my other thoughts:
- @roll could you please take a look at this? It is a list of all the Frictionless Data "products". Can you read through the descriptions in column C (New Descriptions) and let us know if you have any edits? These descriptions will then be updated on their respective github repositories. Also, do you have any suggestions for text for the spaces with '???' ? Thanks!
- I wonder if @pwalsh would be helpful for the specifications descriptions? This isn't my area of expertise.
- It might be nice to have a column for if an item is currently being developed/worked on or if it is stagnant. We have so many projects, and some of them aren't current, which is confusing for our users (and for me, TBH), so it might be nice to have that noted somewhere. Maybe the 'Status' column could have an option of 'Stagnant' or something like that?
- Lots of the spaces with '???' are projects that (I think) aren't being worked on anymore

**Comment by Irio** [comment]
@lwinfree We just added a "Stagnant" status. 👌

**Comment by roll** [comment]
@lwinfree 
I think it's good descriptions. Also, github allows adding tags to repositories. Maybe it's even more important than descriptions for outside visibility.

**Comment by Irio** [comment]
Status: let's timebox this review until tomorrow. We can always return to this later on.

**Comment by Irio** [comment]
FIXED. The taxonomy is done, with positive feedback from people who interacted in this issue. I also asked @johanricher and @pwalsh for feedback. Johan verbally gave some input over video today.
