### ISSUE TITLE
What are the current FD product(s) and how do they fit together?

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/project#385]
When I implement improvement measures on my website, I want to know what's the current state of products and features as well as the connection between them, so that I can answer questions like "Do we need new products?", "How do our products fit together?" etc...

## Acceptance criteria

* [x] List of the products in the FD Products [spreadsheet table](https://docs.google.com/spreadsheets/d/1qByu4qw56hFUdJIY5IOC7d8TQBud-k31J6720hg1h2w/edit?folder=1BgnX2LkS5ksrzS1OyC1js7cO0AuMz6oP#gid=1252612369)
* [x] Every item has a description
* [ ] ~~Diagram / Notes of their relation~~ Moved to https://github.com/frictionlessdata/project/issues/397
* [x] Gap analysis on current products / subproducts

## Tasks

* [x] Do a quick research on the FD products
* [x] List them in the spreadsheet
* [x] Add descriptions and other basic info 
* [ ] ~~(?) Create a diagram illustrating their relation~~ Moved to https://github.com/frictionlessdata/project/issues/397
* [x] A gap analysis on current product / subproducts
* [x] Suggest new descriptions to make the projects more welcoming to new users
* [x] State status of each of the projects e.g., stable, unstable

**Comment by rufuspollock** [comment]
@cabral i think this is a bit tough for @dipeshkhadkaa to do at this stage.

I think this needs someone with a good grasp of the project e.g. me 😉 - i can do this with someone so they learn.

/cc @johanricher @cbenz do you want to get involved?

**Comment by dipeshkhadkaa** [comment]
@cabral I am trying to add as many products as I can including the tools from the website. 
 Also, I have posted my questions as a hypothesis for which rufus has answered in above comment.

**Comment by Irio** [comment]
In [the sheet](https://docs.google.com/spreadsheets/d/1qByu4qw56hFUdJIY5IOC7d8TQBud-k31J6720hg1h2w/edit?usp=sharing) named "Products," you will find a list of all the products I could identify from the list of websites and repositories. It contains product names, clusters (type of product and purpose), major links, official descriptions, suggestions of better descriptions, and comments. The comments should help to address the state of each product – a definitive state will require more time for testing each of the tools.

I'm moving the task of creating the diagram of products to a specific issue and closing this one. The information present in the previously mentioned sheet should be sufficient to create such diagram. Also, it gives a great understanding of what Frictionless Data means in practice nowadays. I'm eager to see it more visually.
