### ISSUE TITLE
What are the job stories overall for the project (and the website and properties)?

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/project#387]
When I am planning to implement improvement measures on my website, I want to know what the overall job stories for the project are, so that I can set clear goals and make a flawless plan of improvement.

WIP draft of job stories is here: https://docs.google.com/document/d/1e5vxPs918-HOlPXjPJYKv8YUwWBAKXk6-_V9j3cCn1g/edit#

## Acceptance criteria

* [x] A list of prioritised job stories 
* [x] A shortlist of <= 5 epics

## Tasks

* [x] Create an Inbox with all existing work
  * [x] Copy over existing user stories from trello https://trello.com/b/MGC4RpTZ/frictionless-data-user-stories
* [x] Create a list of job stories

**Comment by Irio** [comment]
I started drafting a list of job stories based on what we currently have: https://hackmd.io/@irio/SkSCFxBCS

**Comment by rufuspollock** [comment]
Major work today on overall job stories for key users. Now need to move down to website and properties specifically.

**Comment by rufuspollock** [comment]
FIXED. Both high level and site(s) specific job stories are now done https://docs.google.com/document/d/1e5vxPs918-HOlPXjPJYKv8YUwWBAKXk6-_V9j3cCn1g/edit#
