### ISSUE TITLE
What is our current brand (purpose, narrative, logo etc)

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/project#388]
A description of the current brand

* the narrative
* the logo
* other key assets (e.g.site theme etc)

## Acceptance

* [x] A document listing key items

## Tasks

* [x] Narrative and (implicit) Purpose
* [x] Logo and other assets (e.g. website style)

**Comment by rufuspollock** [comment]
FIXED. See https://docs.google.com/document/d/10TKHQCo4wcKAno1HNwvSouH-OEWNXfJt7vF_zuDDCbg/edit#
