### ISSUE TITLE
Create a new sitemap based on user journeys

### ISSUE THREAD

**Issue by monikappv** [frictionlessdata/project#389]
When I am planning to improve the usability of my website, I want to make sure it's structure is well thought out and easy to follow, so that I can offer the users a flawless journey through the website.

## Acceptance criteria

* [x] list of user journeys (e.g. in google docs)
* [x] new sitemap (based on the user journeys). They should explicit say what's an internal/external page.
* [x] Diagram with the new sitemap

## Tasks

* [x] create a list of their user journeys 
* [x] generate a new sitemap (based on the user journeys) https://hackmd.io/VQ8hetjZRKGW0kOj-io9uA

**More specifically, on user journeys**

* [x] Move the content from HackMD to https://docs.google.com/document/d/1e5vxPs918-HOlPXjPJYKv8YUwWBAKXk6-_V9j3cCn1g/edit# and create a "User Journeys" header at the top of the document.
* [x] Create a visualization for these user journeys. (not top priority or required)
* [x] @monikappv - Move visualization to the document, too.
* [x] Create visualization for the sitemap (example in the HackMD)
* [x] Show, for each user journey, how the user would need to navigate in the sitemap to have answers.

**Comment by augusto-herrmann** [comment]
For comparison, take a look at the sitemap for [Linked Data Fragments](https://linkeddatafragments.org/). IMHO it might not be ideal, but it seems easy to find what you want (*my own comments in parenthesis*):

* Concept (*show me what it is* :thinking:)
* Data (*show me some real world examples* :mag_right:)
* Software (*what tools can I use with it* :hammer_and_wrench:)
* In depth (*more like a FAQ, just digging deeper into "what it is", actually* :bulb:)
* Specification (*show me the docs* :book:)
* Publications (*scholarly stuff* :microscope:)

This could serve as inspiration for the new sitemap.

**Comment by Irio** [comment]
I started drafting a mix of sitemap with a table of contents/needs in the scratchpad. Planning on finishing a first version, and to move to a Google Doc for collecting feedback, tomorrow. https://hackmd.io/@rufuspollock/B1kTsCJAS#14-Jan-2020---Draft-of-sitemaptable-of-contents

**Comment by Irio** [comment]
@lwinfree @jobarratt This is an excellent time to gather early feedback about the sitemap. I finished the first iteration and addressed some comments from @monikappv.

In [Design and Architecture](https://docs.google.com/document/d/1Dg6KWFPcY2hCs3KfCQi8LhATr96EvGJTtkCXd_Fax6Q/edit?usp=sharing), under the section "List of Pages," you will find a list of pages, where each contains – roughly ordered from top to bottom – a list of what should contain.

Tomorrow I plan to sketch wireframes together with @monikappv. This will put these ideas to test. Hopefully, it will give us a better idea if these contents work together or not, and if something crucial it's missing or defective. We can always schedule a call to do this review through video, too.

**Comment by lwinfree** [comment]
Hey @Irio I've requested access to the doc and will give feedback soon :-)

**Comment by lwinfree** [comment]
@Irio OK I've taken a look & made a few comments. I think I can give better feedback after you and Monika have done the wireframes. I'm having a bit of trouble imagining what the pages will look like, so maybe we can do a call and go over the wireframes sometime? Thanks!

**Comment by monikappv** [comment]
User journeys (Personas + Actions)

* DecisionMakers
![decisionmaker](https://user-images.githubusercontent.com/56799741/72788343-66483780-3c3a-11ea-8eb2-5fbc578cc77b.png)

* Researchers
![researcheretc2](https://user-images.githubusercontent.com/56799741/72788328-60eaed00-3c3a-11ea-869a-2d30f47ae98d.png)
**NOTE: Same applies for Data Scientists, Data Engineers, Software Engineers**

**Comment by rufuspollock** [comment]
@monikappv these are a list of user stories or job stories not a user journey. A journey would be a flow through the site or product. Can we get some user journeys? And if you want to keep these i would put them in the job stories doc.

**Comment by Irio** [comment]
The sitemap diagram looks complex, but, hopefully, it gets easier to understand when looking to specific sections or to user journeys. While putting the sitemap in a diagram, I had this trade-off between functionality and appearance – I favoured the former when forced to. It's generated by text using Mermaid. The source code for the diagrams is available in [this HackMD](https://hackmd.io/@irio/BycVUDNbI).
 
The homepage has a navigation bar and a footer, both present on every page of the site. In terms of organization, there are two different ways of browsing information on the site: through "problems," or job stories as described in the Issue Tree, or through the directory of  products, linked in the header.

![mermaid-diagram-20200121151617](https://user-images.githubusercontent.com/667753/72812940-bd620280-3c62-11ea-8463-2fe420907273.png)

User journeys are here: https://docs.google.com/document/d/1e5vxPs918-HOlPXjPJYKv8YUwWBAKXk6-_V9j3cCn1g/edit#heading=h.sj1qhujcl9s0

The homepage has a navigation bar and a footer, both present on every page of the site. In terms of organization, there are two different ways of browsing information on the site: through "problems," or job stories as described in the Issue Tree, or through the directory of  products, linked in the header.

---

As an example, the user journey 5, available in the documented linked above: **As a decision maker, I want to see who's involved in the initiative.**

![mermaid-diagram-20200121152154](https://user-images.githubusercontent.com/667753/72813834-4f1e3f80-3c64-11ea-8c0f-63c39a2af505.png)

**Comment by rufuspollock** [comment]
FIXED. See Site Map section in Design doc https://docs.google.com/document/d/1Dg6KWFPcY2hCs3KfCQi8LhATr96EvGJTtkCXd_Fax6Q/edit#heading=h.sjqsjbmvc7eu and associated HackMD https://hackmd.io/@irio/ry6LRnaZ8
