### ISSUE TITLE
CMS for Frictionless Data

### ISSUE THREAD

**Issue by monikappv** [frictionlessdata/project#390]
Context: at some point we are going to want to edit/updatethe FD website(s)

**Is the current software / tooling suitable for what we want?** 
If not, what options do we have?

## Acceptance criteria

* [x] What we have
* [x] What are the key needs
* [x] List of options
* [x] Selected option

## Tasks

* [x] What do we have atm
* [x] Figure out what we want/need (key criteria)
* [x] What are other options
* [x] Play around with Vuepress and Gatsby 
* [x] How does what we have match up against that
* [x] Prioritised list
* [x] Compare the winner-CMS to Gridsome
* [x] Take a look at https://docusaurus.io/

### Needs / Wants

* 1 site or 2(+) sites: Main site, specs site, docs site (?) -- This gets into "job stories" a bit
  * e.g. do we have specs separate from the main site? 
    * Yes: because then specs can get versioned, can updated separately, can commit and reference issues etc
    * No: nice to be together
* Can build off git / markdown backend
* JAMStack-y

### Current system

Uses lektor

### Options

Lightweight, static, developer oriented (we can edit markdown), structured data aspect ...

* Vuepress
* Gatsby
* ~~Gridsome~~
* (Jekyll) - we prefer javascript now!
* (Lektor)
* (Wordpress) (prefer SSG / JAM - but could maybe show up as content API for blog section??)

#### Vuepress vs. Gatsby 

* both Vuepress and Gatsby meet the above listed requirements. 
* which is the best static site generator depends on the language you are comfortable with
* Gatsby is way more popular/has bigger community than Vuepress
* Vuepress is more simple/minimalistic than Gatsby
* Although both are beginner friendly, Vuepress is perhaps more beginner friendly (for non-devs)
* Gatsby offers an IDE tool for building Gatsby websites (GraphQL)

Since it's hard to choose based on that, here is a comparison of the libraries they are based on 
**Vuepress = Vue-based, Gatsby = React-based**

Vue Is Better Than React in the Following Scenario:
* Up-to-date documentation and simpler syntax.
* Smaller, faster, and flexible.
* Rich HTML templates to provide ease in development.

React Is Better Than Vue.js When:
* There’s a requirement to build mobile apps.
* Professional and great community support to solve any issue.
* Need to build large-scale apps.
* Light-weight and easy version migrating.

--> Gatsby is more complex and according to [dzone](https://dzone.com/articles/reactjs-vs-vuejs-comparison-of-popular-frameworks) Vuepress is more suitable for documentation websites 
--> **Vuepress is the winner!**

#### Vuepress vs. Gridsome

* both are Vue-based and meet the requirements
* Vuepress has bigger community than Gridsome
* Gridsome has GraphQL (IDE)
* Vuepress is geared mainly for documentation websites
* Gridsome can accommodate any markdown-based and vue-based static sites
* Vuepress is more minimalistic/simple/beginner friendly than Gridsome
* Gridsome = Gatsby but not React-based but Vue-based
* Gridsome's development seems to be going slower

--> if we want more simple/minimalistic documentation site --> **Vuepress**
--> if we want more customized (and not necesserily just documentation site) --> **Gridsome**

---> we will stick to **Vuepress**

#### Vuepress vs. Docusaurus

> VuePress has many similarities with Docusaurus - both focus heavily on content-centric website and provides tailored documentation features out of the box. However, VuePress is powered by Vue, while Docusaurus is powered by React. If you wanted a Vue-based solution, VuePress would be a decent choice.

* both meet the requirements
* Vuepress has bigger community than Docusaurus
* both are geared mainly for documentation websites
* Vuepress is powered by Vue, Docusaurus by React (see comparison Vue vs. React above)
* Vuepress is aesthetically nicer  

--> we stick to **Vuepress**

**Comment by rufuspollock** [comment]
@monikappv a bunch of this is done e.g. we know what we have atm. I've created a shortlist of options etc. I suggest updating. Also playing around with vuepress and gatsby would be at end of list or at least after what are the options (you are playing around so you have a sense of how these options work and which is preferable).

**Comment by rufuspollock** [comment]
@monikappv can you update on how you got on here today and maybe set out briefly your plan of investigation / try out of those two options (gatsby and vuepress).

**Comment by monikappv** [comment]
@rufuspollock 
my plan of investigation included reading about them, installing them, playing with them + creating small websites, reading what people said about them, and comparing them. 

here is my research --> https://hackmd.io/DXC6JK7fQkaZMdC9CurZRQ?both

**Comment by rufuspollock** [comment]
@monikappv great, can you add the steps / tasks into the description of the issue (btw, in general i don't want to read external links unless i have to, please *summarize* in here if you can).

**Comment by monikappv** [comment]
@rufuspollock I updated the description also with the comparison summary of Vuepress vs. Gridsome... you can have a look and let me know your thoughts.

**Comment by monikappv** [comment]
@rufuspollock moved the issue to the 'done' column...have a look and close it if you think it's ok.

**Comment by rufuspollock** [comment]
@monikappv one last entry -  can you take a quick look at https://docusaurus.io/

**Comment by monikappv** [comment]
@rufuspollock done.. see the description.

**Comment by rufuspollock** [comment]
FIXED. We are going with vuepress. (NB: @roll  may want accordions in the sidebar ToC 😄and we can do that 👍  )
