### ISSUE TITLE
Experiment with Vuepress for the new FD.io website (Dec 19)

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/project#393]
## Acceptance criteria

* [x] ported Specs page on Vuepress
  * screenshot below
* [x] short tutorial on how to create a custom Vuepress Theme
  * whole version here --> https://hackmd.io/735I6NgXQ7WPAWvtLd6QoQ?both
  * summary below
* [x] spreadsheet of all existing F11 pages
  * https://docs.google.com/spreadsheets/d/1qByu4qw56hFUdJIY5IOC7d8TQBud-k31J6720hg1h2w/edit#gid=710398809

## Tasks

* [x] Try out how to create a custom vuepress theme
* [x] Try to port one content page from lektor (start with specs)
* [x] Make a spreadsheet of all existing pages / content (already have in sitemap) so we can plan how they migrate
* [x] Provide a link to the repo with your demo site in it (probably in your personal github space for now) - see below
* [x] Deploy your site somewhere - you could just use github pages or something like zeit or surge etc
* [x] Research tailwind css + see if there is a tailwind vue setup

## [Summary] How to create a custom Vuepress theme

1. Install [VuePress](https://vuepress.vuejs.org/guide/getting-started.html)

2. Create a .vuepress/theme directory 
To write a theme, create a .vuepress/theme directory in your docs root, and then create a Layout.vue file...

3. From there it’s the same as developing a normal Vue application. It’s entirely up to you how to organize your theme.

### Vue.js app structure

* node_modules
* public
  * flavicon.ico etc...
  * **index.html** 
* src
  * assets
  * components
    * Helloworld.vue etc... 
  * **App.vue**
  * **main.js** 
* .gitignore
* babel.config.js
* package-lock.json
* package.json
* README.md

### Learnings

* can use Vue DevTools to debug your custom theme
* third-party library [Bootstrap vue](https://bootstrap-vue.js.org/) - has a lot of build-in components and CSS already written so you don't have to worry about styling
* Vuepress tends to put its styles in small files, clearly defined by purpose. The convention is to put a /styles/ directory in the theme's root directory.
* `<style scoped/>` = CSS limited to the particular component
* Vetur - nice plugin for VScode to help and color the vue syntax for you
* If you don't set sidebar: auto, and also don't config themeConfig.sidebar at .vuepress/config.js, the sidebar will not be shown.
* If you set sidebar: auto, the sidebar should only leverage the active page's headers as the sidebar's links. (h1/h2/h3)
* If you configured themeConfig.sidebar, the sidebar will automatically display the page's links according to your settings. the default depth is 1, which extracts the h2 headers (pageTitle/h1/h2). Setting it to 0 disables the header links, and the max value is 2(pageTitle/h1/h2/h3)

## Ported Specs page 

![specspage](https://user-images.githubusercontent.com/56799741/71417726-88688d00-266f-11ea-94f9-fcc6eafc5f08.png)

## Tailwind CSS [quick research]

* there is a tailwind vue setup --> see https://markus.oberlehner.net/blog/setting-up-tailwind-css-with-vue/

## Link to demo site 

https://monikappv.github.io/vuepress-exp/

## Link to source 

https://github.com/monikappv/vuepress-exp

**Comment by monikappv** [comment]
* the spreadsheet with fd.io pages is done - see https://docs.google.com/spreadsheets/d/1qByu4qw56hFUdJIY5IOC7d8TQBud-k31J6720hg1h2w/edit#gid=710398809
* started looking for sites with nice themes/structure - draft is here https://hackmd.io/1PJBO-bpRaepFpGMnhuwfQ. I will put the best ones in the description as soon as I gather more good examples.

**Comment by monikappv** [comment]
@rufuspollock 

done and moved to 'done'.. you can review and close the issue if you think it's okay.

**Comment by rufuspollock** [comment]
@monikappv great job 👏 

@monikappv to complete this thoroughly can you 

* Provide a link to the repo with your demo site in it (probably in your personal github space for now)
* deploy your site somewhere - you could just use github pages or something like zeit or surge etc


Small comments on your learnings

* generally we want to use tailwindcss rather than bootstrap though we are not religious about it (see if there is a tailwind vue setup)

Re 

> started looking for sites with nice themes/structure - draft is here https://hackmd.io/1PJBO-bpRaepFpGMnhuwfQ. I will put the best ones in the description as soon as I gather more good examples.

I think this could be a new separate issue about designing the theme (can you open an issue for that and move that info there)

**Comment by Irio** [comment]
To deploy to GitHub Pages, you can probably use https://github.com/JamesIves/github-pages-deploy-action.

1. Enable the action to the repository.
    <img width="1008" alt="Screenshot 2020-01-02 at 16 07 54" src="https://user-images.githubusercontent.com/667753/71673855-20562d00-2d7a-11ea-9988-c06b2090bf8d.png">
2. Get a GitHub access token to use in the build and deploy step of the configuration.
3. Setup the action with a configuration similar to this:
	```
	name: Build and Deploy
	on: [push]
	jobs:
	build-and-deploy:
		runs-on: ubuntu-latest
		steps:
		- name: Checkout
		uses: actions/checkout@v1

		- name: Install
		run: |
			npm install
			npm run docs:build

		- name: Build and Deploy
		uses: JamesIves/github-pages-deploy-action@releases/v3
		with:
			ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
			BRANCH: gh-pages # The branch the action should deploy to.
			FOLDER: docs/.vuepress/dist # The folder the action should deploy.
	```
4. Ensure GitHub Pages is configured to run in the `gh-pages` branch.
5. Trigger the GitHub action.
6. The website should be live at https://monikappv.github.io/vuepress-exp/ (or https://monikappv.github.io/vuepress-exp/vuepress-exp/ too).

**Comment by Irio** [comment]
The site is live at https://github.com/Irio/vuepress-exp, with source in https://github.com/Irio/vuepress-exp.

**Comment by monikappv** [comment]
Also live at https://monikappv.github.io/vuepress-exp/, with source in https://github.com/monikappv/vuepress-exp

**Comment by monikappv** [comment]
FIXED.
