### ISSUE TITLE
Websites for Inspiration for Frictionless Data

### ISSUE THREAD

**Issue by monikappv** [frictionlessdata/project#395]
Find sites that can provide inspiration both on theme and layout.

## Acceptance criteria

* [x] "moodboard" of websites containing nice elements/sections/colors etc.. 

## Tasks

* [x] look for websites with nice themes a/o structure
* [x] put the best ones in a list 
* [x] write/show what's good about them
* [x] take screenshots of nice elements/sections/colors
* [x] create a moodboard 

### What we want

* lightweight
* clean
* simple
* minimalistic
* pure
* efortless
* white-ish
* clear structure
* clear tagline
* give a sense of what we are doing and what problems we/our tools are solving

### What we avoid 

* too white / grey-ish / boring
* no accent color / no highlight
* chaos, messiness
* too many info "islands" ...e.g. see below

![](https://i.imgur.com/xeR9iKP.png)

### Moodboard landing page

![export_canvas_tryagain-200106_2211](https://user-images.githubusercontent.com/56799741/71853507-55e57800-30e4-11ea-9a9f-3a455459e68f.png)

### Moodboard docs page 

![export_canvas_project-200106_2222](https://user-images.githubusercontent.com/56799741/71853517-5da51c80-30e4-11ea-92f3-764685cd044f.png)

### Cool websites as a whole (landing + docs)

* Dimer https://dimerapp.com 
* SnazzyDocs https://snazzydocs.com/
* Kentico https://kentico.github.io --> imaging a white background here instead of the current blue-ish one
* Vuepress https://vuepress.vuejs.org/
* Laravel https://laravel.com/

### Full research and moodboard [scratch pads]

* moodboard - https://hackmd.io/ghy5Fn6bTMq29OYjX3oTgw?both 
* research websites - https://hackmd.io/1PJBO-bpRaepFpGMnhuwfQ?both

**Comment by monikappv** [comment]
started looking for sites with nice themes/structure - draft is here https://hackmd.io/1PJBO-bpRaepFpGMnhuwfQ. I will put the best ones in the description as soon as I gather more good examples.

**Comment by monikappv** [comment]
Moodboard in progress --> https://hackmd.io/ghy5Fn6bTMq29OYjX3oTgw ...to be continued..

**Comment by Irio** [comment]
FIXED. The HackMD's contents have been added to the description of this issue. Although not necessarily a complete moodboard, we are satisfied with what has been produced for the time being.

**Comment by johanricher** [comment]
Let me add just one good example that I know and that could inspire you also: https://fr.openfisca.org/
