### ISSUE TITLE
Send our user survey and collate responses (Dec 19)

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/project#396]
Send the user survey created in #379 to relevant communities

## Acceptance

* [x] Posted on f11data gitter channel
* [ ] ~Sent to okfnlabs (mailing list)~ Not doing it at this moment
* [x] Tweeted by okfn and okfnlabs
* [x] banner containing user survey on fd.io
* [x] sent to data hackers slack channel
* [x] Posted on reddit / hacker news (?)

Overall game: 30 responses from community, 70 from others 

## Tasks

* [x] Add the user survey as banner to current site (see archive.org of datahub.io to see how we used to do this) - pull request sent - https://github.com/frictionlessdata/website/pull/204
* [x] Post on gitter channel

**Comment by Irio** [comment]
I just posted over the Gitter channel (frictionlessdata/chat).

**Comment by monikappv** [comment]
created a branch called banner-survey, added banner on the landing page with short text and link to the user survey (like it used to be on datahub), and sent pull request - https://github.com/frictionlessdata/website/pull/204

**Comment by Irio** [comment]
FIXED. Survey has been posted and we have responses. https://forms.gle/NoANyhzSN7nxfLqb9
