### ISSUE TITLE
Diagram with all the Frictionless Data products

### ISSUE THREAD

**Issue by Irio** [frictionlessdata/project#397]
The spreadsheet called [Frictionless Data Brand and Website Improvement Dec 2019 Issue Tree [PUBLIC]](https://docs.google.com/spreadsheets/d/1qByu4qw56hFUdJIY5IOC7d8TQBud-k31J6720hg1h2w/edit?usp=sharing) should contain a thorough list of all the products under Frictionless Data (sheet named "Products"). They are also clusterized in "type of project" and "purpose." We want to visualize all of this to understand the relationships, the overlapping, and the gap between projects. It should help newcomers to quickly get what Frictionless Data is for and what it currently contains.

Ideally, this visualization is not created in an image editor, but code-generated (see https://mermaid-js.github.io/mermaid/). This way, we can more easily update it, either manually or automatically based on some data source.

## Acceptance

- [ ] Visualize all the different products in a diagram https://coggle.it/diagram/XgnrNnDSoHVRjRso/t/frictionless-data-product-ecosystem
- [ ] (Separate?) Visualize the relationships ...

## Tasks

* [ ] Boot a coggle
* [ ] Add all the items
* [ ] Organize them (maybe in different ways)

**Comment by rufuspollock** [comment]
Started work here: https://coggle.it/diagram/XgnrNnDSoHVRjRso/t/frictionless-data-product-ecosystem

**Comment by rufuspollock** [comment]
WONTFIX / DUPLICATE of #403 #404 and #384
