### ISSUE TITLE
[v2][epic] Design and Architecture of FD

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/project#398]
Design and architect the website(s) and the general info architecture of FD project.

https://docs.google.com/document/d/1Dg6KWFPcY2hCs3KfCQi8LhATr96EvGJTtkCXd_Fax6Q/edit?folder=1BgnX2LkS5ksrzS1OyC1js7cO0AuMz6oP#heading=h.4sfh9t60g6xa

Needs already done: see Jobs to Be Done for website plus high level

## Acceptance

* [x] A structural map from jobs to be done to products (many-to-many with meaning in the links)
  * [x] **What is the key organizing mental model (coming in - what do users think about)**
  * [x] Map from that to products
* [x] A list of key "user" (jobs to be done) journeys
* [x] A list of products with structure / taxonomy (at the low level e.g. specs vs tools)  #384 
  * [x] List of products
  * [x] Taxonomy (Is there a primary organizing mental model for products different from this ...?)
* [x] Wireframes / Content Templates for product pages (e.g. github readmes or dedicated page on website)
* [x] List of key non-product content for the site e.g. "about", news, community, help etc **see #411**
  * [x] Draft of content and/or implementation for some of the key ones of these where content not obvious (e.g. news content is obvious but structure may not be) **see https://docs.google.com/document/d/1Dg6KWFPcY2hCs3KfCQi8LhATr96EvGJTtkCXd_Fax6Q/edit#heading=h.c271r9ndand7**
* [x] Design principles for the info architecture **see https://docs.google.com/document/d/1Dg6KWFPcY2hCs3KfCQi8LhATr96EvGJTtkCXd_Fax6Q/edit?folder=1BgnX2LkS5ksrzS1OyC1js7cO0AuMz6oP#heading=h.kiqhmchksjpw**
* [x] Choices re one site or many and how these are woven together ... **see https://docs.google.com/document/d/1Dg6KWFPcY2hCs3KfCQi8LhATr96EvGJTtkCXd_Fax6Q/edit?folder=1BgnX2LkS5ksrzS1OyC1js7cO0AuMz6oP#heading=h.iu4tgyohq3**

## Tasks

* [x] Mental model of world of data work (integration) #403
* [x] A structural map from jobs to be done to products (many-to-many with meaning in the links) - #404 
* [x] A list of key "user" (jobs to be done) journeys #389
* [x] A list of products with structure / taxonomy (at the low level e.g. specs vs tools) #384
* [x] Wireframes / Content Templates for product pages (e.g. github readmes or dedicated page on website)
* [x] List of key non-product content for the site e.g. "about", news, community, help etc
  * [x] Draft of content and/or implementation for some of the key ones of these where content not obvious (e.g. news content is obvious but structure may not be)

**Comment by Irio** [comment]
First sketch for the homepage:

![Frictionless Data main landing page sketch](https://user-images.githubusercontent.com/667753/72531686-4eefff80-3872-11ea-97d0-7ca48efe5cef.png)

https://docs.google.com/drawings/d/1oOQ9ZIiahQ_KctBnyrIucbzqTcQOLXu6f-TEqwtHRXc/edit?usp=sharing

*Done by @monikappv and I, minutes ago*

Monday, we probably want to work on reviewing the issues and focusing on [finishing the sitemap](https://github.com/frictionlessdata/project/issues/389) before keep iterating on this design task.

cc @lwinfree @rufuspollock @jobarratt

**Comment by lwinfree** [comment]
@monikappv & @Irio  y'all this is great! 😍 My only change would be to move "Main products" above "Trusted by", but that's not a deal breaker for me. I'm excited to see more!

**Comment by jobarratt** [comment]
I would agree this is looking absolutely great! Simple, clear and a big improvement. Easy to navigate and users will be at ease and familiar with what they are looking for. 

Only a 2 tiny comments but ike lilly they are not deal breakers. 

1.  consider removing the headings "Main products" and "Trusted by" entirely. I think it's clear what they are already. 

2. wonder if "contribute" and "community" should be both be in the menu? I'm not sure what the plan i for these pages so perhaps my comment can be ignores.

**Comment by monikappv** [comment]
@rufuspollock @jobarratt @lwinfree @Irio 

here is the first sketch of the "problem landing page" (e.g. in this case "Pull dataset"). Any feedback is welcome.

* the hexagon diagram is the same as the one on the landing page, so that people can still have an overview of all of the problems that we are solving, with the difference that the particular "problem" (e.g. "Pull dataset") would be highlighted here.
* the second section should contain more content re "pull dataset"
* the screenshot is not so relevant, just an example. It could be either screenshot or even a gif like here https://www.storyblok.com/ (see the how it works section on the landing page)
* not sure how good this idea is, but according to the sketch the content of the "how it works" section would change depending on the tool that the user has chosen to "investigate" (by clicking on the how it works button under the tool description) 

![Frictionless data Problem Landing Page sketch](https://user-images.githubusercontent.com/56799741/72627245-d01fc300-3954-11ea-90e9-e1bab414aba0.png)

**Comment by lwinfree** [comment]
This makes sense to me!

**Comment by rufuspollock** [comment]
FIXED. All done now. See description for links to outputs etc.
