### ISSUE TITLE
[v2][epic] Content Creation and Updating

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/project#400]
To create the content of all key pages:

* Jobs to be done pages
* Product pages
* Initiative pages (about, news etc)
* Repos are updated

## Acceptance

* [x] Website content is written

## Tasks

* [x] Review all existing FD.io pages so that we know what can be re-use in the next version (and with what changes) **Done over the spreadsheet linked below. Sheet fdio-pages**
* ~~FD repos: generic changes (e.g. a common template) and specific changes (plus priority for rolling this out i.e. what repos first)~~ move to #400
* [x] List of contents to be written #411 
* [x] Write the first draft of content and put on the site
  * [x] Name, tagline etc for Jobs
  * [x] Name, tagline for products

## Copy Needed for Following

*May want to move to spreadsheet to track!*

https://docs.google.com/document/d/1Dg6KWFPcY2hCs3KfCQi8LhATr96EvGJTtkCXd_Fax6Q/edit?folder=1BgnX2LkS5ksrzS1OyC1js7cO0AuMz6oP#heading=h.iu4tgyohq3

**Comment by rufuspollock** [comment]
FIXED. All content is there for now.
