### ISSUE TITLE
[v2] Brand Design

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/project#401]
Brand Design (now narrative is done)

Generate the brand design assets and guide e.g. logo, ... 

See this style guide https://docs.google.com/document/d/17JiW15VZCDT_I24R4kHTel2NqOJuZKvCl5OCN1qpQfE/edit#

## Acceptance

* [x] Name
* [x] Tagline
* [x] Logo
* [x] Style guide: fonts, colors
* [x] tone of voice
* ~~Poster example~~
* [x] Mock front page

## Tasks

* [x] Logo options
* [x] Logo selected
* [x] "Moodboard"
* [x] Font selection
* [x] Tone of voice

**Comment by rufuspollock** [comment]
FIXED. Outputs from designer are here https://docs.google.com/document/d/17JiW15VZCDT_I24R4kHTel2NqOJuZKvCl5OCN1qpQfE/edit#

**Comment by monikappv** [comment]
FIXED. Tone of voice is now done. See https://docs.google.com/document/d/17JiW15VZCDT_I24R4kHTel2NqOJuZKvCl5OCN1qpQfE/edit#
