### ISSUE TITLE
[v2][epic] FD Website Theme

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/project#402]
Live website theme for vuepress supporting the custom pages we have plus instructions on how to use this for editors

## Acceptance

* [x] Theme sketch in XD/Adobe Indesign (Wireframes)
  * [x] Front page
  * [x] Blog page
  * [x] Product (pattern/tool) page
* [x] Live theme
  * [x] Framework to use e.g. tailwind vs bootstrap
* [x] There are working HTML pages, stylized, of each of every existing page.
  * [x] Home page - https://next.frictionlessdata.io/
  * [x] Job to be done page https://next.frictionlessdata.io/job/document-dataset/
  * [x] Product page https://next.frictionlessdata.io/products/data-package
  * [x] Blog listing page https://next.frictionlessdata.io/blog
  * [x] Blog post page https://next.frictionlessdata.io/blog/2020/01/23/nes-tool/
  * [x] Team page http://next.frictionlessdata.io/team/
  * [x] Contributing page http://next.frictionlessdata.io/contribute/

### Design

* [x] Examples of websites for inspiration - #395 
* [x] Collect all mockups for pages to this issue
* [x] Wireframes
  * [x] Front page  
  * [x] Product (pattern/tool) page
  * [x] Job to be done
  * [x] Blog index page
  * [x] Team page
  * [x] Content page e.g. blog or other classic content
* [x] Mockups (see below)
  * [x] Front page 
  * [x] One other 
  * [x] ~~Quickly mock a footer~~ moved to #425 

Note: 
- From doing the front page we would benefit from more detailed wireframes / mockups as it would make translation quicker.
- We could include, for example, the images we plan to use (so that html work is just copying those over)

### Implement theme

* [x] Research (briefly) theming in vuepress
* [x] Choose a HTML+CSS framework: between vuepress default theme, bootstrap and tailwind (default is tailwind) => Tailwind
 * [x] Implement base theme
* [x] Implement front page
  * [x] build the page 
  * [x] finish styling and design
* [x] do the team page - try to get the layout close to vuejs.org/ team page
  * [x] stub the page (structure, basic content)
  * [x] do the styling 
* [x] do the blog index page
  * [x] Try to think about the standard frontmatter / metadata each post should have and use that info
  * [x] stub the page (structure, basic content)
  * [x] ~~fix the tags~~ moved to #425 
  * [x] fix date format
  * [x] fix the images 
    * [x] put default image for the ones that don't have frontmatter image
  * [x] fix pagination @Irio @monikappv 
  * [x] fix styling
* [x] do the blog individual page - shall we just use Page (?)
  * [x] stub the page 
  * [x] fix styling
* [x] do the contribute page - default page
  * [x] add content 
* [x] fix styling of the products individual page
* [x] Reintroduce default fonts / coloring of vuepress
* [x] Crudely re-apply vuepress theme default styles (reuse index.styl ... - is there a way w/o copying and pasting)
* [x] ~~Tweak the logo (with text and thicker f)~~ moved to #425 @sylvie
* [x] ~~Have markdown in html e.g. front page code samples - see https://github.com/vuejs/vuepress/issues/257~~ moved to #425 
* [x] make sure the sidebar appears on some pages where we need it 

#### Front Page

* [x] Front page hexagons ... => would like them to be editable (svg / js stuff) @Irio @MuhammadIsmailShahzad https://github.com/frictionlessdata/project/issues/421

### Front page 

![](https://i.imgur.com/GiFErZQ.png)

### Job to be done Page

![](https://i.imgur.com/w6GgWbM.png)

### Blog Index Page

![blog-index-page](https://user-images.githubusercontent.com/56799741/73361724-30e0c100-42ae-11ea-848b-42057e287fc6.png)

### Blog Individual Page

![blog-individual-page](https://user-images.githubusercontent.com/56799741/73361739-39d19280-42ae-11ea-934e-94d1793c746f.png)

### Team Page

![team-page](https://user-images.githubusercontent.com/56799741/73361747-3ccc8300-42ae-11ea-8f4c-0540c09d8895.png)

### Product Page

![product-page](https://user-images.githubusercontent.com/56799741/73370141-68566a00-42bc-11ea-84c3-836155e3b497.png)

### Front page 

![](https://i.imgur.com/jRs7J6I.png)

![](https://i.imgur.com/c4G0CAa.png)

### Blog index page

![](https://i.imgur.com/CMbCV3J.png)

### Blog post page

![](https://i.imgur.com/8K8FhgE.png)

### Frontmatter template

```
---
title:
intro: 
pub_date:
heroImage:
author:
tags: 
article-type: (=case study, pilot, grantee profile etc.)
---
```

:::warning
Note: atm a lot of inconsistency in the frontmatter attributes' names e.g. for  image - "imgage", "image", "subject_img", "obj_image" etc..
**make sure they are all aligned**
:::

## Most current mockup home page

![Landing-mockup](https://user-images.githubusercontent.com/56799741/74055219-42317800-49e8-11ea-9497-21f06b2509b9.png)

**Comment by rufuspollock** [comment]
## Original Wireframes from @monikappv a few weeks ago

### Front page 

landing page wireframes based on the Moodboard from https://github.com/frictionlessdata/project/issues/395 (see below)

![image](https://user-images.githubusercontent.com/56799741/72227068-05b55c80-35a1-11ea-8806-f27894a7df4c.png)

![landing1](https://user-images.githubusercontent.com/56799741/72227097-3b5a4580-35a1-11ea-8696-5ed21ac4bcfb.png)
![landing2](https://user-images.githubusercontent.com/56799741/72227098-3b5a4580-35a1-11ea-9c89-843c35976a06.png)
![landing3](https://user-images.githubusercontent.com/56799741/72227099-3bf2dc00-35a1-11ea-9ee5-90c8b9631abf.png)
![landing4](https://user-images.githubusercontent.com/56799741/72227100-3bf2dc00-35a1-11ea-9724-08eb41c5c802.png)
* **Note: background image is just an example here** (see above)
![landing5](https://user-images.githubusercontent.com/56799741/72227102-3c8b7280-35a1-11ea-84ed-8e5cf27e826c.png)
![landing6](https://user-images.githubusercontent.com/56799741/72227103-3c8b7280-35a1-11ea-9361-48ff1eabc001.png)
![landing7](https://user-images.githubusercontent.com/56799741/72227104-3c8b7280-35a1-11ea-9988-f7aabbed2eee.png)

**Comment by monikappv** [comment]
FIXED. See the acceptance criteria for link to website where stuff is working. Some smallish final fixes in follow up issue #425
