### ISSUE TITLE
[v2] Mental Model of the World of Data

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/project#403]
Child of #398

## Acceptance

* [x] List of jobs to be done / tasks
* [x] Diagram of those

## Tasks

* [ ] **What is the key organizing mental model (coming in - what do users think about)** - can use High Level Jobs to be done
* [ ] Do a diagram (research and then build)

**Comment by Irio** [comment]
Current version: https://docs.google.com/drawings/d/1JvDqPLMaE5yMhZ7Gv_mZFG0iHLPc-AKSJMKEnRcmT9E/edit?usp=sharing

<img width="1069" alt="Screenshot 2020-01-09 at 10 45 39" src="https://user-images.githubusercontent.com/667753/72056614-39586400-32cd-11ea-8ecb-7ce4d355f999.png">

**Comment by rufuspollock** [comment]
FIXED. See diagram plus detailed analysis of those steps in sheet https://docs.google.com/spreadsheets/d/1qByu4qw56hFUdJIY5IOC7d8TQBud-k31J6720hg1h2w/edit#gid=2050389930
