### ISSUE TITLE
[v2] Moodboard for Brand Design

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/project#405]
Create a moodboard for brand covering colors, fonts, general look and feel.

## Acceptance

* [x] Moodboard covering colors, fonts, general look and feel

## Tasks

* [x] Boot moodboard (e.g. in Adobe XD)
* [x] Start collecting stuff
* [x] create the moodboard

## Moodboards

* it is more about **the feeling / mood of a website**, not necessarily showing concrete elements / sections
* all of them are very different from each other on purpose

### Moodboard [1]

in case we want to keep the current colors...

![export_canvas_moodboard2-200116_1205](https://user-images.githubusercontent.com/56799741/72567974-b3857b80-38bf-11ea-8721-6ab74af079ed.png)

### Moodboard [2]

in case we don't want to keep the current colors...

![export_canvas_moodboard-200117_0032](https://user-images.githubusercontent.com/56799741/72574468-d882ea00-38d1-11ea-81a6-b0e36b17cd9d.png)

### Moodboard [3]

in case we don't want to keep the current colors...

![export_canvas_moodboard3-200117_1517](https://user-images.githubusercontent.com/56799741/72625180-fc394500-3950-11ea-9b63-ab41c2351711.png)

**Comment by monikappv** [comment]
@rufuspollock @lwinfree @jobarratt here are some moodboard suggestions (see issue description)... I am basically improvising since I don't really have a sense of what you are expecting / wanting from the new website. Any feedback is welcome. 

It's possible that none of them is even close to your vision of the website, but it's still a good starting point as we can at least find out what we don't want :smile: 

Feel free to give me some directions / advices / cool website examples etc.

**Comment by lwinfree** [comment]
I like 1, but I am partial to the orange :-) Thanks!

**Comment by rufuspollock** [comment]
@monikappv great and a final choice on colors will probably come from the branding person and the design work - see #401

**Comment by monikappv** [comment]
FIXED.

**Comment by jobarratt** [comment]
This is great, i like 1 and 2, but prefer colours to 1.
