### ISSUE TITLE
[v2] Write content templates for README's

### ISSUE THREAD

**Issue by Irio** [frictionlessdata/project#406]
Once we're done reviewing user journeys and sitemap, we want to actually write new templates to ensure that every non-archived repository follow the same minimal standards. To achieve that, we need to define these standards.

Part of #398.

## Acceptance criteria

* [x] There's is a list of requirements that every non-archived repository needs to follow. Possibly, we should know also the purpose of each of the items e.g., code quality and CI badges to communicate trust and stability. https://docs.google.com/spreadsheets/d/1qByu4qw56hFUdJIY5IOC7d8TQBud-k31J6720hg1h2w/edit#gid=191297608
* [x] There's a real project example following these standards.
* [x] Real markdown template. As an example:

    ```
    # Title of the project
    *Slogan*

    <code quality/CI badges>

    What it does in concret terms

    # How it works

    Description

    code snippet

    ...
    ```

## Tasks

* [x] do a research and take notes
  * [x] what do READMEs include 
  * [x] good README examples
  * [x] cool sections / ideas
* [x] create a list with requirements + the purpose of each item
* [x] create a template based on that

---

# Research outcome:

A Readme file gives the user a brief idea about what the project is about, which language it has used, what are the terms and conditions, licensing, how many forks/stars the repository has got, what your project can do, screenshots of your running application, etc.

### Logo, title, description

![](https://i.imgur.com/GppoUsx.png)

### Features 

![](https://i.imgur.com/dUrh2kO.png)

### Getting started (prerequisites, installation)

![](https://i.imgur.com/20DrT5b.png)

### Badges

* how many forks or stars this repository has
* how many issues have been raised till now
* is it still maintained by the developer
* what licensing it has
* other valuable information for the user to decide whether they’d want to contribute to this repository or not

**Note:** easy way to create badges - https://shields.io/

### License section

**Note:** Whatever license you choose, always read the Terms very carefully since they contain the right to your software.

The three major licenses used are :

* Apache License v2.0
* GNU General Public License v3.0
* MIT License

### perhaps Screenshots a/o gifs

* show your working prototype side by side rather than putting one image per paragraph
* make sure you also have the image uploaded in your repository as well 

### Feedback section

pointing to gitter chat / twitter etc.

![](https://i.imgur.com/beLkvXW.png)

![](https://i.imgur.com/LcitPAZ.png)

### Links section 

pointing to the main website / other tools / libs / forums 

![](https://i.imgur.com/Jjrc1Bt.png)

### Support section

pointing to channels users can get support on

![](https://i.imgur.com/CoF65g4.png)

### Logo at the top

![](https://i.imgur.com/7eqb3CP.png)

### TOC

![](https://i.imgur.com/jhykhMd.png)

### Contribute section

![](https://i.imgur.com/SRhVxwU.png)

### Why should you care section

could be a good way of low-key presenting problem-solution (e.g. what problems the tool solves)

![](https://i.imgur.com/VS1v0K3.png)

### About section

![](https://i.imgur.com/51yOv0b.png)

---

## List of README's contents:

https://docs.google.com/spreadsheets/d/1qByu4qw56hFUdJIY5IOC7d8TQBud-k31J6720hg1h2w/edit#gid=191297608

## Cool READMEs

https://github.com/sourcerer-io/sourcerer-app#readme
https://github.com/gitpoint/git-point#readme
https://github.com/dowjones/react-dropdown-tree-select#readme
https://github.com/IgorAntun/node-chat#readme
https://github.com/ai/size-limit#readme (only license & badges missing)

## README Template

```
[logo]

# Project title

[Badges]

Project description

[TOC]

## Features

* feature 1
* feature 2

~ perhaps [screenshot/GIF] ~

## Usage

code snippets

## Getting started

### Prerequisites

* requirement 1 
* requirement 2 

### Installation

code snippets

## Changelog

v1.1
v1.0

## Support

reach out to us on the following channels:
* gitter chat 
* channel 2

## Contribute

this is how you can contribute..

## Feedback

"Any questions or suggestions?
You are welcome to discuss it on [gitter] and [twitter]"

## License

```

**Comment by Irio** [comment]
FIXED.  That's excellent, I believe we are ready to follow this template in a first README review.
