### ISSUE TITLE
[v2][epic] Review and plan the necessary changes in README's

### ISSUE THREAD

**Issue by Irio** [frictionlessdata/project#408]
Once we are finished on listing all the user journeys and thinking about the sitemap, we will have good idea of what people want/need to know once they arrive on GitHub repositories. Since the quality of README's differ, we want to create standards and ensure all the code snippets work as documented.

Related to #398.
Depends on https://github.com/frictionlessdata/project/issues/406.

## Acceptance criteria

* [x] There is a list of issues related to the changes needed in repository README's. They should have an specific label e.g., `README changes`.
* [x] There is a list of contents that need to be written e.g., short description about each project, standardized project categories, tags, links.
* [x] There is a list of working/not working code snippets for every current README.
* [x] Give labels for the issues, such as for difficult levels.

## Tasks

* [ ] Review everything!

**Comment by stellamarissb** [comment]
Doing a general review of the README files of all 88 repositories is done. 

Here it is our checklist https://docs.google.com/spreadsheets/d/1Xz-9xKqSs2IyX5_Gpa_Y-yPb00G0JH4LcRWeVB-vZRY/edit?pli=1#gid=0

And here there are our reviews https://docs.google.com/document/d/1xFyyrAtcDkjRTXaza5lcZxPzRP71ExiudfjE4e1Gc8U/edit#heading=h.u7gtl9mfvnxy 

Time it took in total: 

Stellamaris: 8h30
Rob              8h30

Let us know if this reaches your expectations. Looking forward to your response if any correction needed.

**Comment by lwinfree** [comment]
Hey @Irio, @roll and I have already done some work here when we were redoing the docs. Can we chat either here or on a call to get on the same page?

**Comment by roll** [comment]
Hi @Irio, yes, please sync with me if you have plans for updating labels and doing more than the description updates on the readmes. We just need to ensure that the proposed changes will not break the current maintenance process. 

Another thing is that in general I and @lwinfree formed a different vision of what is desired state of documentation. In our eyes is what we need to do is redirect users (except for contributors) from readmes to the high-level documentation. We've got a lot of feedback that looking up for information in so many different places (our libs' readmes) is really bad user experience. One of the scenarios we have is leaving only API references in the readmes and, as I said, transferring code snippets etc to FD's docs (we're not yet sure that it's the way to go)

BTW It's great to have all the code snippets reviewed :+1:

**Comment by rufuspollock** [comment]
FIXED. Just to note @Irio did sync with @roll 😄 and all looks good.

@Irio feel free to add anything else as a completion comment.
