### ISSUE TITLE
Migrate blog posts to the new content management system

### ISSUE THREAD

**Issue by Irio** [frictionlessdata/project#409]
Since we are creating a new website, we want to ensure that contents that won't require changes, such as published blog posts, are properly migrated.

## Acceptance criteria

* [x] ~We have defined a good content management system for bloging. It has been suggested to use Wordpress, Docusaurus, and Vuepress. The latter will be used in the rest of the website. We should have also understand the reasoning behind this choice.~ Talked to Rufus and Vuepress seems to fulfil the needs here. References that may be helpful to achieve the goal:
    * https://github.com/bencodezen/vuepress-blog-boilerplate
    * Demo: https://vuepress-blog-boilerplate.bencodezen.io/
* [ ] All the blog posts are available and online in the new platform. All images and links work as expected.

## Tasks

* [ ] Rely on Vuepress Blog boilerplate to bring blog-related boilerplate into @monikappv's project.
* [x] @monikappv - Transfer ownership of https://github.com/monikappv/vuepress-exp to Frictionless Data's organization. - https://github.com/frictionlessdata/vuepress-exp
* [ ] Copy blog posts from https://frictionlessdata.io/articles/ to the new platform/repository.
* [ ] Copy blog posts from https://frictionlessdata.io/field-guide/ to the new platform/repository.
* [ ] Ensure everything renders as expected.
* [ ] Ensure everything is properly tagged e.g., case-study, tutorial, news.
* [ ] Ensure everything is deployed and live in the production environment, with continuous deployment.

## Steps to migrate one post

1. Get one page from the spreadsheet that has not been migrated.
2. Open the source code for this page in the original website.
3. Create a new folder inside `site/blog` in the new website. This new folder should contain a timestamp and the slug used in the original page. *Please see examples - in the spreadsheet and in the other folders present in `site/blog`*.
4. Create `README.md` inside this new folder.
5. Copy the source code `content.lr` into the new `README.md` file. Also, copy all the images present in the folder of the original website.
6. Preview this new page in localhost to look for abnormalities.
7. Fix links (anchors and images) as recommended in https://github.com/frictionlessdata/project/issues/417. Ensure they work – or at least the ones linking to migrated pages.
8. Get attributes at the top and bottom of the file to look like the other blog posts already migrated.
9. Put a `sidebar: false` attribute to the top of the `README.md`.
10. Test again in the browser.
11. Commit.
12. Mark the page as migrated in the spreadsheet.

**Comment by monikappv** [comment]
ownership transferred to FD - https://github.com/frictionlessdata/vuepress-exp.

**Comment by RobGrootjen** [comment]
@Irio @monikappv 

I created a new branch called blog_transfer. I pushed the content folder with all the articles/blogs in it. Let me know if this reaches your expectations. Looking forward to your response if any correction needed.

**Comment by Irio** [comment]
@RobGrootjen Can you work on migrating these new articles posted by @lwinfree in the current website, too? Thanks. https://github.com/frictionlessdata/website/pull/210

**Comment by rufuspollock** [comment]
INVALID / DUPLICATE. Because blog posts are not that different from other posts it does not make sense to separate this so work on all content migration is now centralized in #217

**Comment by augusto-herrmann** [comment]
> INVALID / DUPLICATE. Because blog posts are not that different from other posts it does not make sense to separate this so work on all content migration is now centralized in #217

Now I'm confused, @rufuspollock. #217 has nothing to do with this. What do you say this a duplicate of? Did you mean #400?

**Comment by rufuspollock** [comment]
@augusto-herrmann correct. Fixed link.
