### ISSUE TITLE
Review every code snippet in the repositories

### ISSUE THREAD

**Issue by Irio** [frictionlessdata/project#410]
Given that we are improving the whole experience around Frictionless Data, we want to ensure that everything that we say reflects the true nature of the libraries we offer. To achieve this status, we want to ensure that code snippets/examples in the README's work as documented.

This issue does not expected someone to run each of the dozens of repositories, end-to-end, and write pages of critics and suggestions. The purpose of this issue is to estimate the effort of reaching this quality level. My (Irio) personal feeling is that no repository will be perfect; most will lack, for instance, a command to change the node version or simple stuff like this. The goal is to focus on analysing the overall quality.

## Acceptance criteria

* [ ] There is a document containing one entry for each of the active repositories listed in the [products spreadsheet](https://docs.google.com/spreadsheets/d/1qByu4qw56hFUdJIY5IOC7d8TQBud-k31J6720hg1h2w/edit#gid=55598434).
* [ ] For each product, there's an estimation of the experience of following the README instructions. e.g., "The examples stopped working on the second snippet," or "It lacks a working end-to-end example of X."
* [ ] For repositories requiring only a few changes in code snippets, ideally, we have suggestions of the changes/pull requests.

## Tasks

* ?

**Comment by lwinfree** [comment]
FIXED.
