### ISSUE TITLE
List contents that need to be written

### ISSUE THREAD

**Issue by Irio** [frictionlessdata/project#411]
After having a sitemap, we want to start writing the contents for the website. Much will be based on the reviewed brand, other part can be based of, or copied, from the current website. Following that direction, we want to have a list of contents that needs to be written.

High level list of contents. It doesn't have to be "single sentence with 10 words describing product X in concrete terms for this specific public." But "single sentence for the general public, longer description for developers..."

## Acceptance criteria

* [x] There's a list of contents that require a copywriter.
* [x] Writing is priorited/categorized. In other words, it says something will go to the page X, to page Y; also, it says what needs to be written first (home page and product landing pages, for instance).
* [ ] ~~The writing has someone assigned to.~~ [this is not essential for now]

## Tasks

* [x] Map requirements for each of the proposed pages.
* [x] Post this publicly and ask for feedback.
* [x] Move the list to a Google Doc. -> https://docs.google.com/document/d/1XHbRgivaz_JkYLOi3nRBmYIIfjtbETbpYm_OYmQzTZY/edit
* [x] Create new issue for producing the content and reviewing it. #400

**Comment by Irio** [comment]
Based on the ideas/wireframes, we need copy for the following:

### Home page

[Wireframe](https://docs.google.com/drawings/d/1oOQ9ZIiahQ_KctBnyrIucbzqTcQOLXu6f-TEqwtHRXc/edit)

* [ ] Slogan for Data Package.
* [ ] Slogan for Data Pipelines.

### Navigation - About

* [ ] Short introduction about the original prototype, release, and its reception by the community.
* [ ] Explanation of the current leadership: Open Knowledge + Datopian. Why? Is there a reason for having a non-profit and a for-profit?
* [ ] Answers for:
  * Is Frictionless Data an organization? An open source community? Profit or not for profit?

### Navigation - Products

* [ ] Explanation of what needs to happen for a product to be promoted to this page.
  * Can anyone make a pull request to add any product? Does it have to belong to the Frictionless Data organization, figuratively or on GitHub?
* [ ] Call for action to contribute to this list.
  * Either by adding new projects or suggesting updates to the table contents themselves.


### Navigation - Documentation

*---*

### Navigation - Specifications

* [ ] Paragraph explaining how specifications are useful in the context of Frictionless Data.
* [ ] Brief introduction to how people may start reading the specifications to understand them as parts of a group.
* [ ] One sentence explaining each specification.

### Navigation - Contribute

* [ ] Call to action for the multiple ways of contributing to the project.
* [ ] Explanation of what are the most welcoming issues for first time contributors (relating to tags "help wanted" and "first-time contributor")
  * References:
    * https://opensource.guide/how-to-contribute/
    * https://www.firsttimersonly.com/

### Navigation - Blog

* [ ] Call to action for learning more about the project using the listed blog posts, talks, and papers.

### Footer - Team

* [ ] 1-2 social networks of each product maintainer or leadership member.

### Footer - Help

* [ ] Describe what are the prefered ways of contact.
  * GitHub? Which repository? When to use Gitter? How about StackOverflow? And Frictionless Data/OKF/Datopian social networks?
* [ ] Describe expectations for free and paid support. Also, how and by whom paid support can be provided.

### Product - Data Package

* [ ] A paragraph introducing the product – what it does, why it's useful, no accompany diagrams and the introductory video. Specially for newcomers.
 
### Problem - Pull Dataset page

[Wireframe](https://docs.google.com/drawings/d/1v8vJ-Wku3l8HpnIN8nF6p8KVAh4KiRDBTenvuiDC-w8/edit)

* [ ] Tweet-long description of how each product – in [Job Stories -> Our Offer (Primary)/Our Offer (Secondary)](https://docs.google.com/spreadsheets/d/1qByu4qw56hFUdJIY5IOC7d8TQBud-k31J6720hg1h2w/edit#gid=2050389930) – solves this problem.
 
### Problem - Push Dataset page

[Wireframe](https://docs.google.com/drawings/d/1v8vJ-Wku3l8HpnIN8nF6p8KVAh4KiRDBTenvuiDC-w8/edit)

* [ ] Tweet-long description of how each product – in [Job Stories -> Our Offer (Primary)/Our Offer (Secondary)](https://docs.google.com/spreadsheets/d/1qByu4qw56hFUdJIY5IOC7d8TQBud-k31J6720hg1h2w/edit#gid=2050389930) – solves this problem.

### Problem - Validate Dataset page

[Wireframe](https://docs.google.com/drawings/d/1v8vJ-Wku3l8HpnIN8nF6p8KVAh4KiRDBTenvuiDC-w8/edit)

* [ ] Tweet-long description of how each product – in [Job Stories -> Our Offer (Primary)/Our Offer (Secondary)](https://docs.google.com/spreadsheets/d/1qByu4qw56hFUdJIY5IOC7d8TQBud-k31J6720hg1h2w/edit#gid=2050389930) – solves this problem.

### Problem - Do Initial Data Exploration page

[Wireframe](https://docs.google.com/drawings/d/1v8vJ-Wku3l8HpnIN8nF6p8KVAh4KiRDBTenvuiDC-w8/edit)

* [ ] Tweet-long description of how each product – in [Job Stories -> Our Offer (Primary)/Our Offer (Secondary)](https://docs.google.com/spreadsheets/d/1qByu4qw56hFUdJIY5IOC7d8TQBud-k31J6720hg1h2w/edit#gid=2050389930) – solves this problem.

### Problem - Pipeline Transformations page

[Wireframe](https://docs.google.com/drawings/d/1v8vJ-Wku3l8HpnIN8nF6p8KVAh4KiRDBTenvuiDC-w8/edit)

* [ ] Tweet-long description of how each product – in [Job Stories -> Our Offer (Primary)/Our Offer (Secondary)](https://docs.google.com/spreadsheets/d/1qByu4qw56hFUdJIY5IOC7d8TQBud-k31J6720hg1h2w/edit#gid=2050389930) – solves this problem.

### Problem - Version Dataset page

[Wireframe](https://docs.google.com/drawings/d/1v8vJ-Wku3l8HpnIN8nF6p8KVAh4KiRDBTenvuiDC-w8/edit)

* [ ] Tweet-long description of how each product – in [Job Stories -> Our Offer (Primary)/Our Offer (Secondary)](https://docs.google.com/spreadsheets/d/1qByu4qw56hFUdJIY5IOC7d8TQBud-k31J6720hg1h2w/edit#gid=2050389930) – solves this problem.

### Problem - Have a Data Hub page

[Wireframe](https://docs.google.com/drawings/d/1v8vJ-Wku3l8HpnIN8nF6p8KVAh4KiRDBTenvuiDC-w8/edit)

* [ ] Tweet-long description of how each product – in [Job Stories -> Our Offer (Primary)/Our Offer (Secondary)](https://docs.google.com/spreadsheets/d/1qByu4qw56hFUdJIY5IOC7d8TQBud-k31J6720hg1h2w/edit#gid=2050389930) – solves this problem.

### Problem - Document Dataset page

[Wireframe](https://docs.google.com/drawings/d/1v8vJ-Wku3l8HpnIN8nF6p8KVAh4KiRDBTenvuiDC-w8/edit)

* [ ] Tweet-long description of how each product – in [Job Stories -> Our Offer (Primary)/Our Offer (Secondary)](https://docs.google.com/spreadsheets/d/1qByu4qw56hFUdJIY5IOC7d8TQBud-k31J6720hg1h2w/edit#gid=2050389930) – solves this problem.

### Problem - Create Visualizations page

[Wireframe](https://docs.google.com/drawings/d/1v8vJ-Wku3l8HpnIN8nF6p8KVAh4KiRDBTenvuiDC-w8/edit)

* [ ] Tweet-long description of how each product – in [Job Stories -> Our Offer (Primary)/Our Offer (Secondary)](https://docs.google.com/spreadsheets/d/1qByu4qw56hFUdJIY5IOC7d8TQBud-k31J6720hg1h2w/edit#gid=2050389930) – solves this problem.

### Problem - Do Analysis & Machine Learning page

[Wireframe](https://docs.google.com/drawings/d/1v8vJ-Wku3l8HpnIN8nF6p8KVAh4KiRDBTenvuiDC-w8/edit)

* [ ] Tweet-long description of how each product – in [Job Stories -> Our Offer (Primary)/Our Offer (Secondary)](https://docs.google.com/spreadsheets/d/1qByu4qw56hFUdJIY5IOC7d8TQBud-k31J6720hg1h2w/edit#gid=2050389930) – solves this problem.

### Problem - Store Dataset page

[Wireframe](https://docs.google.com/drawings/d/1v8vJ-Wku3l8HpnIN8nF6p8KVAh4KiRDBTenvuiDC-w8/edit)

* [ ] Tweet-long description of how each product – in [Job Stories -> Our Offer (Primary)/Our Offer (Secondary)](https://docs.google.com/spreadsheets/d/1qByu4qw56hFUdJIY5IOC7d8TQBud-k31J6720hg1h2w/edit#gid=2050389930) – solves this problem.

### Problem - Quickly Edit Dataset page

[Wireframe](https://docs.google.com/drawings/d/1v8vJ-Wku3l8HpnIN8nF6p8KVAh4KiRDBTenvuiDC-w8/edit)

* [ ] Tweet-long description of how each product – in [Job Stories -> Our Offer (Primary)/Our Offer (Secondary)](https://docs.google.com/spreadsheets/d/1qByu4qw56hFUdJIY5IOC7d8TQBud-k31J6720hg1h2w/edit#gid=2050389930) – solves this problem.

### Problem - Find Datasets page

[Wireframe](https://docs.google.com/drawings/d/1v8vJ-Wku3l8HpnIN8nF6p8KVAh4KiRDBTenvuiDC-w8/edit)

* [ ] Tweet-long description of how each product – in [Job Stories -> Our Offer (Primary)/Our Offer (Secondary)](https://docs.google.com/spreadsheets/d/1qByu4qw56hFUdJIY5IOC7d8TQBud-k31J6720hg1h2w/edit#gid=2050389930) – solves this problem.

### Problem - Orchestrate Data Platform page

[Wireframe](https://docs.google.com/drawings/d/1v8vJ-Wku3l8HpnIN8nF6p8KVAh4KiRDBTenvuiDC-w8/edit)

* [ ] Tweet-long description of how each product – in [Job Stories -> Our Offer (Primary)/Our Offer (Secondary)](https://docs.google.com/spreadsheets/d/1qByu4qw56hFUdJIY5IOC7d8TQBud-k31J6720hg1h2w/edit#gid=2050389930) – solves this problem.

### Problem - Meta - Cross-cutting (go across all the others or arise from combining those others) page

[Wireframe](https://docs.google.com/drawings/d/1v8vJ-Wku3l8HpnIN8nF6p8KVAh4KiRDBTenvuiDC-w8/edit)

* [ ] Tweet-long description of how each product – in [Job Stories -> Our Offer (Primary)/Our Offer (Secondary)](https://docs.google.com/spreadsheets/d/1qByu4qw56hFUdJIY5IOC7d8TQBud-k31J6720hg1h2w/edit#gid=2050389930) – solves this problem.

### Problem - Gracefully Scale Scope page

[Wireframe](https://docs.google.com/drawings/d/1v8vJ-Wku3l8HpnIN8nF6p8KVAh4KiRDBTenvuiDC-w8/edit)

* [ ] Tweet-long description of how each product – in [Job Stories -> Our Offer (Primary)/Our Offer (Secondary)](https://docs.google.com/spreadsheets/d/1qByu4qw56hFUdJIY5IOC7d8TQBud-k31J6720hg1h2w/edit#gid=2050389930) – solves this problem.

### Problem - Gracefully Scale Size page

[Wireframe](https://docs.google.com/drawings/d/1v8vJ-Wku3l8HpnIN8nF6p8KVAh4KiRDBTenvuiDC-w8/edit)

* [ ] Tweet-long description of how each product – in [Job Stories -> Our Offer (Primary)/Our Offer (Secondary)](https://docs.google.com/spreadsheets/d/1qByu4qw56hFUdJIY5IOC7d8TQBud-k31J6720hg1h2w/edit#gid=2050389930) – solves this problem.

**Comment by rufuspollock** [comment]
FIXED. All done. See list above.
