### ISSUE TITLE
[v2] Update repository descriptions and tags etc

### ISSUE THREAD

**Issue by Irio** [frictionlessdata/project#412]
Generic changes (e.g. a common template) and specific changes (plus priority for rolling this out i.e. what repos first)

We have proposed changes to the descriptions, so they should be applied to the GitHub repositories.

Priority driven off traffic and importance assessment

## Acceptance criteria

* [x] Descriptions reflect suggestions from the spreadsheet. https://docs.google.com/spreadsheets/d/1qByu4qw56hFUdJIY5IOC7d8TQBud-k31J6720hg1h2w/edit#gid=311025204 (Products sheet)
* [ ] We make good use of repository tags to communicate each project. - NOT HAPPENING NOW - see convo below

## Tasks

* [x] Apply updates to descriptions as per spreadsheet https://docs.google.com/spreadsheets/d/1qByu4qw56hFUdJIY5IOC7d8TQBud-k31J6720hg1h2w/edit#gid=311025204 (Products sheet)
* [ ] Add tags - NOT HAPPENING NOW - see convo below

### Standardize (may be Future)

*This may be future work esp if we move to more docs setup rather than github README*

* [ ] Set out common template for README

**Comment by rufuspollock** [comment]
I've reviewed the spreadsheet with the list of changes and I think it needs quite a bit of work - often there are no suggestions and where there are, the suggestion could be improved I think. I also think we want to focus this on the github repos - so replace fd.io links with the github repo e.g. for specs

`https://github.com/frictionlessdata/specs` rather than `https://frictionlessdata.io/specs`

@lwinfree @roll do you guys want to look into this - we can start by updating the spreadsheet and maybe just with a few and then review and do more.

**Comment by lwinfree** [comment]
Is this issue only about updating the descriptions in the readmes? If so, I am happy with the content in the spreadsheet. It is my understanding that @roll talked with @Irio about the rest of the readme content (the documentation parts) and that the plan is to not have all the documentation in the readmes.

**Comment by rufuspollock** [comment]
@lwinfree yes it is only about updating the github descriptions (not even the readmes afaik).

**Comment by rufuspollock** [comment]
@lwinfree are you and @roll able to look at this in this sprint - it could be nice to have this updated before csvconf - wdyt?

**Comment by lwinfree** [comment]
Yeah @rufuspollock we'll look into it!

**Comment by roll** [comment]
The descriptions are already updated according to the doc.

Regarding tags - is there any evidence that it helps to find our software? I mean I have nothing against tags but we can add the `csv` tag (+10 other formats) to fifty of our repositories. It will take time and bloat the org visual representation - just trying to understand the pros vs cons

TBH this issue feels like a very low priority for me as we might rework our repositories structure soon.

**Comment by lwinfree** [comment]
Thanks @roll! I agree with you regarding tags. Maybe we revisit tagging in the future after it has been decided if the repos structure is changing?

**Comment by rufuspollock** [comment]
@lwinfree looks like most stuff is now done. Do you want to update the description with the status of items (if you can do as per https://playbook.datopian.com/issues-tasks/#completing-tasks that really helps me 😉 ...) then we can close i think ...

**Comment by lwinfree** [comment]
@rufuspollock hey I've updated. If you want to update in the future, please feel free to do so
