### ISSUE TITLE
[v2][epic] FD v2 Operational

### ISSUE THREAD

**Issue by monikappv** [frictionlessdata/project#415]
The new v2 FrictionlessData.io is fully operational.

## Acceptance

* [x] fully operational new website working
* [x] new theme
* [x] old urls still work (wherever possible) via redirects

## Tasks

* [x] Set up vuepress based site #416
* [x] Migrate content #417
* [x] (80%) Write and add new content #400
* [x] (90%) Theme it ... #402 
* [x] Implement redirects so we don't break existing links ... 
* [x] Switch over DNS

### Future

* [ ] Search across all FD websites 

### NTS 30 Jan - what is the critical path?

* [x] Site functioning
  * [x] Blog section http://next.frictionlessdata.io/blog/
  * [x] Team section http://next.frictionlessdata.io/team/
* [x] Site theme @monika
* [x] Content migrated @rob / @stella
  * [x] Specs? (this can be done pretty quickly) @rufus @roll may help
* [x] Front page
  * [x] hexagons - could they wait and we just have list for now ...? Maybe a boxed list just to be able to ship it as soon as possible. https://github.com/frictionlessdata/project/issues/421
* [x] Stubbed product pages
* [x] Jobs to be done pages. Just copy the text from somewhere else.

**Comment by rufuspollock** [comment]
FIXED. All done and now live https://frictionlessdata.io/
