### ISSUE TITLE
Set up the Vuepress website system

### ISSUE THREAD

**Issue by monikappv** [frictionlessdata/project#416]
Implement everything we need technically in the new vuepress-based setup ... 

Probably want at least one example page for each major section working and crudely laid out ...

## Acceptance

Booted website with at least one example page for each major section:

* [x] Basic vuepress based site
* [x] built automatically with github actions
* [x] Some core pages skeletonned
* [x] How to do theming + templating incl multiple pages off one layout (based on a template)
* [x] It's communicating to Google Analytics

Pages

* [x] Home page
* [x] News / Blog
* [x] Team
* [x] Jobs to be Done
* [x] Products
* [ ] ~~About~~ (VueJS does not have about page - do we need one ...?)
* [ ] ~~Documentation~~ (later when clear what we need)

## Tasks

* [x] Install vuepress and have it run
  * [x] Choose whether we build from root or a subdirectory like `site` **From the root**
  * [x] Stub standard vuepress front page
* [x] Implement github actions to build
* [x] Add README.md ~~CONTRIBUTING.md~~ explaining how to contribute
* [x] Install vuepress plugins we may want e.g. footnotes, mermaid (copy from datopian handbook)
* [x] stub content for each page with the structure of you will want
  * [x] job to be done page `/jobs/pull-data/` @irio
  * [x] product page e.g. `/products/data-packages/` @irio
  * [x] about @monika
  * [x] blog (have this from migration content)
* [x] Research how to do theming and have "layout" pages i.e. a whole section using the same template and for those bespoke templates to still have core theme elements **See this extensive summary https://hackmd.io/@rufuspollock/BJ318ubfU**
  * [x] Try it out
  * [x] Work out how we do template inheritance / core
* [x] Blog experiment - may require some research on plugin. See below for tasks.
* [x] Team page **Done. See http://next.frictionlessdata.io/team/**
* [x] Check we can embed html in markdown pages as we need some HTML pages **Yes we can - see below**
* [x] Configure Google Analytics with the VuePress plugin

---

### Theming

Which pages need a different layout than the default one?

* Default page: like a doc page / like vuepress default
* Home page
* Blog listing
* Product / Job pages

Do we want to use vuepress' default layout for all pages (a little bit customized) except for the home page?

Is it more that we have reusable components / snippets of some kind? e.g. hero section etc etc.

Let's not try and work out too much in advance => KISS

Tasks

* [x] Boot the theme
  * Do we extend default theme or roll our own? **KISS: start with it and see where it breaks ...**
    * Default theme is nice esp for docs ...
    * But is there a way to extend? => Yes, via inheritance
    * And does it do enough? Maybe not but we can extend
* [x] Create a layout file
* [x] Customize home
* [x] Apply it to a page **http://next.frictionlessdata.io/products/data-package/**

Learnings

* You can inherit from the base theme
* But you will need to refactor Layout.vue or override probably ultimately ...
  * Refactor into GlobalLayout? No.

---

### Blog experiment

Outcome

* [x] Individual blog page
* [x] Blog index page
* [ ] ~~Notes on how to do it~~ (not really needed, docs are actually quite clear)

Tasks

* [x] Investigate and choose approach **Use plugin plus our own templates based on the examples**
  * Blog generator: https://github.com/bencodezen/vuepress-blog-boilerplate
  * Official blog plugin: https://github.com/vuepressjs/vuepress-plugin-blog
  * Official Blog Theme: https://vuepress-theme-blog.ulivz.com/
* [x] Install plugin https://github.com/vuepressjs/vuepress-plugin-blog
  * [x] Basic config to you our directory structure **It's working http://localhost:8080/website-v2/2018/03/07/well-packaged-datasets/**
* [x] Create blog index page **Done** copied from https://github.com/ulivz/70-lines-of-vuepress-blog-theme/tree/master/layouts
* [x] Customize blog page **Ditto. Showed the title!**

### Team Page

Goal a page looking like https://vuejs.org/v2/guide/team.html (but w/o styling atm)

Source is https://raw.githubusercontent.com/vuejs/vuejs.org/master/src/v2/guide/team.md

* [x] Research how to do "data" directories **Yes, sort of.**
  * Data files and dynamic page generation support https://github.com/vuejs/vuepress/issues/452 => is closed and says there is dynamic page generation. However, point in comments that you can use frontmatter is not perfect e.g. what if i want to load csv
  * Example: https://vuepress-examples.netlify.com/demos/local/
* [x] Stub a list of team members
* [x] Render them in page (custom layout?)

**Comment by rufuspollock** [comment]
FIXED. All done. Result is at https://github.com/frictionlessdata/website-v2/tree/bf58c13860dc0b84dddc2349d86fe42a8688f29f - see especially the .vuepress and its theme directory https://github.com/frictionlessdata/website-v2/tree/bf58c13860dc0b84dddc2349d86fe42a8688f29f/site/.vuepress
