### ISSUE TITLE
[v2][epic] Migrate the content

### ISSUE THREAD

**Issue by Irio** [frictionlessdata/project#417]
Review the existing content and copy the needed pieces of content over to the new website.

A reference for the necessary changes is in this spreadsheet in the sheet "FD.io-pages:

https://docs.google.com/spreadsheets/d/1qByu4qw56hFUdJIY5IOC7d8TQBud-k31J6720hg1h2w/edit?folder=1BgnX2LkS5ksrzS1OyC1js7cO0AuMz6oP#gid=710398809

At this moment, we are using this spreadsheet, sheet "FD.io-pages," to track which of the pages have been migrated and to where. Please use it in your favor.

## Acceptance

* [x] All the blog posts / articles on old site that should be in news are in news
*  ~~Specs exists on new site~~ => moved to #431
* [x] All other content migrated

## Tasks

* [x] Review existing content - what do we need to migrate and where does it go **see [this spreadsheet/FD.io-pages](https://docs.google.com/spreadsheets/d/1qByu4qw56hFUdJIY5IOC7d8TQBud-k31J6720hg1h2w/edit?folder=1BgnX2LkS5ksrzS1OyC1js7cO0AuMz6oP#gid=710398809) for a reference of what to move to where.**
  * [x] Double check this e.g. some items missing
  * [x] Also add newly added articles https://github.com/frictionlessdata/website/pull/210
* [x] Have a template for migrating a file
  * [x] Is it worth a scripting? **No**
  * [x] Determine the standard frontmatter e.g. `date`, `tag(s)` ...
  * [x] Use of `<!-- more -->` for blog excerpts (or use frontmatter explicitly?) https://vuepress.vuejs.org/theme/writing-a-theme.html#content-excerpt  **We used frontmatter**
* [x] Write simple test(s) for content (using cypress) so that we know our correctness going forward **We have one to ensure that the home page loads with 200 status and at least the title, which is at the top of the file, loads without any Javascript errors.**
* [x] Migrate the content in that spreadsheet
  * [x] Schedule / assign the migration
  * [x] Follow steps for page migration below for each page - @stellamarissb is responsible for migrating the six last articles. They are tracked in [the spreadsheet](https://docs.google.com/spreadsheets/d/1qByu4qw56hFUdJIY5IOC7d8TQBud-k31J6720hg1h2w/edit#gid=710398809&range=48:53).
* [x] Implement redirects #423 

### Steps to migrate one page

1. Get one page from the spreadsheet that has not been migrated.
2. Migrate it over (see step by step below)
3. Test on your local machine and view in the browser.
4. Commit.
5. Mark the page as migrated in the spreadsheet with new location

Rinse and repeat :repeat: 

### How to migrate a file over ... 

See example below for this in practice

1. Open the raw source for this page in the original website.
3. Create a new folder inside `site/blog` in the new website. This new folder should contain a timestamp and the slug used in the original page. *Please see examples - in the spreadsheet and in the other folders present in `site/blog`*.
4. Create `README.md` inside this new folder.
5. Copy the source code `content.lr` into the new `README.md` file. Also, copy all the images present in the folder of the original website.
6. Preview this new page in localhost to look for abnormalities.
7. Fix links (anchors and images) as recommended in https://github.com/frictionlessdata/project/issues/417. Ensure they work – or at least the ones linking to migrated pages.
8. Get attributes at the top and bottom of the file to look like the other blog posts already migrated.
    * TODO: specify the standard frontmatter here e.g. tags, date etc
10. ~~Put a `sidebar: false` attribute to the top of the `README.md`.~~

#### Example

Raw content are in LR files, but we want them as Markdown. The differences are subtle, but you should pay attention to the start and the ending of every file.

**Source file and structure**

https://frictionlessdata.io/field-guide/well-packaged-datasets/

Folder: https://github.com/frictionlessdata/website/tree/master/content/field-guide/well-packaged-datasets

Raw file: https://raw.githubusercontent.com/frictionlessdata/website/master/content/field-guide/well-packaged-datasets/contents.lr

**Target file and structure** 

https://frictionlessdata.github.io/blog/2018-03-07-well-packaged-datasets

Raw: https://github.com/frictionlessdata/website-v2/tree/master/site/blog/2018-03-07-well-packaged-datasets

```
title: Well packaged datasets
date: yyyy-mm-dd
intro: There's an art to creating a good collection of data. Improve the quality of your datasets; making use of schemas, metadata, and data packages.
image: ./well-packaged.png
required:
tools: Data Package Creator
sort_key: 1
... add any other keys in original one ...
... (and make a note to discuss them)
```

**Tips**

:warning:  Pay attention to full frictionlessdata.io URLs. Change them to relative URLs e.g.

```
[Data Package specification](http://frictionlessdata.io/specs/data-package/)

should become

[Data Package specification](/specs/data-package/)
```

### Migrating stuff not in blog into blog

The proposal here is that we migrate some current pages that may be perceived as documentation to the new blog. The reason is because they are not necessarily concise or speak well together i.e., link to other pages, completing one another. With this migration, it's important to give every content page a date. Sometimes, this date will be in the Markdown file, others you will have to get in the Git commit that generated such file.

* Work out the date of it from source markdown!

**Comment by ismail-shahzad** [comment]
## Tasks
- [x]  Implement redirects
- [x]  Identify how to do redirects Seems vuepress does this centralized rather than per page and in JS config. See vuejs/vuepress#239. There is also a plugin https://vuepress.github.io/en/plugins/redirect/#installation - seems a little confusing but think it would do the job and can do bulk redirects from a sub-url
- [x]  Make list of all redirects (use spreadsheet)
- [x]  Implement that
- [x]  Test it (by hand? or use automated testing if done above)
## Quick Summary
* I took old and new urls the list from the spreadsheet --https://docs.google.com/spreadsheets/d/1qByu4qw56hFUdJIY5IOC7d8TQBud-k31J6720hg1h2w/edit?folder=1BgnX2LkS5ksrzS1OyC1js7cO0AuMz6oP#gid=710398809 
* Saved them in a list and added them to `router`
* Tested them manually
## Detailed list of steps followed for implementation
see-- https://github.com/frictionlessdata/project/issues/423

**Comment by monikappv** [comment]
FIXED. Everything migrated except a few minor things which are now in #428.
