### ISSUE TITLE
Review older blog posts to see which are out of date and maybe flag for the future

### ISSUE THREAD

**Issue by Irio** [frictionlessdata/project#418]
Originally part of https://github.com/frictionlessdata/project/issues/417, the idea is to deprioritize it for this current sprint.

## Acceptance

* [x] We have a spreadsheet containing the status of each of the all tutorials imported into the new blog. For each of the blog posts, we have information if it's still working, if it's invalid, or if it's up-to-date.

## Tasks

* [x] Review each of the blog posts in the new website
* [x] Annotate if they are still valid, or if they should not be updated anymore
* [x] Annotate if the examples still work or not

**Comment by lwinfree** [comment]
@Irio I'm happy to help with this

**Comment by nirabpudasaini** [comment]
The spreadsheet is updated with the sheet containing all the blog post https://docs.google.com/spreadsheets/d/1qByu4qw56hFUdJIY5IOC7d8TQBud-k31J6720hg1h2w/edit#gid=178944918. The posts now need to be reviewed individually to check for validity and if the examples are working. 

The most common issues from the blog are
1. Most blog have broken links to spec and docs site
2. Few blogs have broken links to other blogs
3. Few blogs have external broken links
4. Few blogs do not display images properly
5. ! and !! were used to show info box in old site but now does not work
6. Few blog post use links like [Tabular Data Packages][tdp] which do not work 
7. Few blog posts are hard to read because of strange line breaks

Additional comments on blog
1. Blog tags are clickable but does nothing
2. Pagination would be a useful additional feature

**Comment by lwinfree** [comment]
I finished this a few weeks ago. The spreadsheet was very helpful!
