### ISSUE TITLE
Verify and fix every broken link in the new website

### ISSUE THREAD

**Issue by Irio** [frictionlessdata/project#419]
Originally part of https://github.com/frictionlessdata/project/issues/417. At this moment, we are aware of the possibility to exist broken links in the main website. This may be caused by the migration, or just that they are linking to websites that just don't exist anymore. We want to fix this.

The spreadsheet may not be necessary if everything is in a single commit message, well documented.

## Acceptance

* [x] There's a list of links that were broken at the time of this task was started --> https://docs.google.com/spreadsheets/d/1qByu4qw56hFUdJIY5IOC7d8TQBud-k31J6720hg1h2w/edit#gid=1953065023
* [x] There are no link broken anymore

## Tasks

* [x] Run a tool such as [broken-link-checker](https://www.npmjs.com/package/broken-link-checker) to help on verifying all the broken links.
* [x] List all the broken links on a spreadsheet
* [x] For each link, there's a fix/decision. Either a correct and updated link, or the decision to remove it.
* [x] Live website has no broken links anymore

---

## Outcome

There was a spreadsheet containing all broken links at the time when the task was started. For each link there was a correction proposal. Each link, when fixed, got deleted from the spreadsheet. For more details see history of the spreadsheet https://docs.google.com/spreadsheets/d/1qByu4qw56hFUdJIY5IOC7d8TQBud-k31J6720hg1h2w/edit#gid=1953065023.

**Comment by mr-vara** [comment]
Please find all broken links [here](https://docs.google.com/spreadsheets/d/1qByu4qw56hFUdJIY5IOC7d8TQBud-k31J6720hg1h2w/edit#gid=1953065023).

**Comment by mr-vara** [comment]
@monikappv The spreadsheet is updated with new data. Please check again.

**Comment by monikappv** [comment]
@mr-vara alright - you can now move on to the correction proposals.

P.S. can you fix the link of the spreadsheet in your comment https://github.com/frictionlessdata/project/issues/419#issuecomment-588168608. The current link is leading to the whole spreadsheet document, but not to the exact sheet.

**Comment by mr-vara** [comment]
Broken links because of the issue with configuration are fixed. Specs site redirection, Page not found and external links are left to be fixed.

**Comment by mr-vara** [comment]
Updated broken links [spreadsheet](https://docs.google.com/spreadsheets/d/1qByu4qw56hFUdJIY5IOC7d8TQBud-k31J6720hg1h2w/edit#gid=1953065023).

**Comment by mr-vara** [comment]
@monikappv Please check the [spreadsheet](https://docs.google.com/spreadsheets/d/1qByu4qw56hFUdJIY5IOC7d8TQBud-k31J6720hg1h2w/edit#gid=1953065023). I've added correction for all broken links including external links. Could you please review that and let me know if I can update that in code.

**Comment by rufuspollock** [comment]
@mr-vara @monikappv can you update on state of this - what remains to be done atm?

@lwinfree this is something you could include as part of the proof review work in #435

**Comment by lwinfree** [comment]
I'll make notes if I find any broken links!

**Comment by monikappv** [comment]
FIXED. See **Outcome** in the issue description.
