### ISSUE TITLE
Diagram of jobs to be done a.k.a. hexagon diagram

### ISSUE THREAD

**Issue by Irio** [frictionlessdata/project#421]
[This diagram](https://docs.google.com/drawings/d/1JvDqPLMaE5yMhZ7Gv_mZFG0iHLPc-AKSJMKEnRcmT9E/edit) is crucial for the new communication we want to have in the new website. We will be showing in almost all the pages, and it's part of the main navigation. For this reason, we want it to be pretty (not ugly, at least), understandable, and allow for interactions. Maybe on hovering on a hexagon, we want to show a balloon with the tagline of the job to be done; or even just change the color in some way. It should respond to clicks, which will redirect to the job page.

There are two main different approaches:

* Low level, such as interacting directly with the canvas.
* High level, such as using a library such as D3.

This issue is part of https://github.com/frictionlessdata/project/issues/415 and https://github.com/frictionlessdata/project/issues/402. 

## Acceptance

* [x] Clicks to a hexagon should redirect to the job page.
* [x] The diagram should not be ugly i.e. as much as possible, run away from tools such as [mermaid](https://mermaidjs.github.io/).

## Tasks

* [x] Specify the needs of this diagram. What we want as an outcome. **It's at the top of this issue.**
* [x] Research different libraries/ways of implementing this diagram. **We're going with honeycomb.**
* [x] Implement a prototype in JSFiddle or VuePress.
* [x] Implement inside VuePress.
* [x] Design it i.e. give it colors, font-size, etc.
* [x] Implement interactions.
* [ ] ~Double check if it's easily possible to create semantically correct links using Honeycomb and SVG.js. In the first tries, we couldn't easily add a raw SVG as contents to a `Hex` object. As a reference: https://alligator.io/svg/hyperlinks-svg/ At this moment, the references exist only in Javascript. There are `onClick` events on each hexagon that open the expected anchor. Not ideal.~ Deprioritized from this week. Moved to https://github.com/frictionlessdata/project/issues/424.

## References

* https://bl.ocks.org/mbostock/5249328
* https://github.com/d3/d3-plugins/tree/master/hexbin
* https://github.com/larsvers/d3-hexgrid
* https://www.visualcinnamon.com/2013/07/self-organizing-maps-creating-hexagonal.html
* https://medium.com/@Flauwekeul/honeycomb-hexagon-grids-in-javascript-555d2f9ac54f
* **https://github.com/olihawkins/d3-hexjson**
  * [ ] Can we create a HexJSON file for something that it's not a map?
* https://www.redblobgames.com/grids/hexagons/
* https://www.redblobgames.com/grids/hexagons/implementation.html
* https://github.com/flauwekeul/honeycomb
* https://jsfiddle.net/Flauwekeul/3bd6sa9r/

## On the Honeycomb proposal

* https://github.com/flauwekeul/honeycomb
* https://jsfiddle.net/Flauwekeul/3bd6sa9r/
* Margin between hexagons https://github.com/flauwekeul/honeycomb/issues/37

----

# Semantically correct links

As stated in the issue for creating the diagram, currently, the anchors just exist in Javascript. People using screen readers are the ones most affected, but also it impacts everyone. For instance, browsers don't show the destination of the link while hovering a hexagon. Thus, it may not be top priority, but it's still very important to be done.

In the initial analysis made by @MuhammadIsmailShahzad and I, we couldn't easily figure out a way to do so.

## Acceptance

* [ ] We have semantically correct anchors in the diagram.

## Tasks

* [ ] Research/read the source code of svg.js and honeycomb-grid to understand if it's really a feature not supported.
* [ ] Read the source code of these libs to understand how to extend them.
* [ ] Possibly open an issue in the most appropriate project asking for help.
* [ ] Implement the change.

## References

https://alligator.io/svg/hyperlinks-svg/

**Comment by Irio** [comment]
@MuhammadIsmailShahzad and I created the following implementation based on the original proposal for the graph. During the research, we found out that this type of graph is sometimes referred as honeycomb or hexagonal grid.

It's currently implemented [in a CodePen](https://codepen.io/irio/pen/wvawgpp), but we tested and it should work seamlessly inside VuePress. For the time being, we just thought it was easier to do it outside. 

![Feb-04-2020 15-12-46](https://user-images.githubusercontent.com/667753/73755962-20758e00-4767-11ea-9b52-a023e50b0abf.gif)

**Comment by Irio** [comment]
FIXED. https://github.com/frictionlessdata/website-v2/commit/1c2d3fc0cf8c0d70452281a4866045dc3697183a

<img width="1181" alt="Screenshot 2020-02-06 at 18 16 56" src="https://user-images.githubusercontent.com/667753/73961453-e8a84b00-490c-11ea-8bd8-24007d8372be.png">

**Comment by lwinfree** [comment]
Reopening as this was never incorporated

**Comment by lwinfree** [comment]
closing and noting this was added to the Datopian site but not the Frictionless site.
