### ISSUE TITLE
[epic] Review and triage current backlog of specs issues

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/project#504]
We currently have 97 open issues and 3 open PRs and we have not done a proper triage in a while. There a fair number of issues that are duplicate or could merge.

When visiting the specs tracker I want to know what's planned to be implemented and what's not so that I know where the specs are going (and could contribute)

When maintaining the specs I want to note  be overwhelmed by all the info so that I can do my job efficiently

## Acceptance

* [ ] Have triaged issues into a triage board
  * [ ] Obsolete / superseded (may just close these)
  * [ ] wontfix
  * [ ] v1.1 priority
  * [ ] v1.1 maybe
  * [ ] Pattern priority
* [x] Have a project board for work in progress **https://github.com/frictionlessdata/specs/projects/1**
* [ ] Prioritized backlog in that board 

## Tasks

* [ ] Boot a project board for work in progress
* [ ] Boot a 
* [x] Do some initial triage (mainly for WiP) ~ 2h *
* [ ] Do a systematic triage
  * [ ] What's obsolete / superseded / wontfix
  * [ ] Of what isn't, what's a pattern and what's not ... and sort into backlog columns for that (could use existing labels ...) 
     * too bad that github boards don't seem to allow allocating issues to a list via labels ...
  * [ ] What's the priority of that ...

**Comment by rufuspollock** [comment]
Started work on some triage into work in progress a couple of weeks ago

![image](https://user-images.githubusercontent.com/180658/82111087-a7f97280-9742-11ea-8e17-ce7926f7743e.png)
