### ISSUE TITLE
Merge fellows.frictionlessdata.io/blog/ into frictionlessdata.io/blog/

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/project#508]
@lwinfree what do you think of merging the Frictionless Data Fellows blog into the main site blog (with an appropriate tag so you can have a dedicated page to get all the posts).

Why? We are generally aiming to reduce the number of difference entry points so that people find stuff more easily (e.g. I did not even know about the fellows blogs ...). It would also increase the audience for these blog posts

## Tasks

* [ ] Agree whether or not to do this
* [ ] If so, copy over the posts
* [ ] Implement redirect on fellows site to frictionlessdata.io

**Comment by lwinfree** [comment]
Sure re-posting the blogs makes sense to me. I don't want to redirect though as the fellows website is a useful part of our programme, but reposting makes sense.

**Comment by rufuspollock** [comment]
OK, the issue with not redirecting is we end up with content in *two* places which tends further to confusion. Obviously it's livable with but it violates our default "DRY" principle and one thing in one place efforts 😉
