### ISSUE TITLE
Improve functionallity of Table Schema Catalog website

### ISSUE THREAD

**Issue by monikappv** [frictionlessdata/project#511]
We want to automate the adding-a-new-table-schema-process as much as possible.

The idea is to reduce the steps needed for a new table schemas to be added *as much as possible* so that it is easier for both contributor and maintainer.

**Goal [1]:** 
1. adding a new table schema section in the `catalog.json` and 
2. creating a PR
should be everything the **Contributor** is expected to do.

![contributor_TS](https://user-images.githubusercontent.com/56799741/82829696-8fb0f280-9ebc-11ea-8ddb-220a82560a01.png)

**Goal [2]:**
1. reviewing + merging the PR and
2. running a script `new-schemas.js`
should be everything the **Maintainer** is expected do.

![Maintainer_TS](https://user-images.githubusercontent.com/56799741/82829697-917ab600-9ebc-11ea-8773-a59a1816cc89.png)

**Goal [3]:** everytime when you run the script:
1. new directory gets added
2. name of the directory = name of the table schema, low-cased and separated by `-` 
3. a new README.md gets added to the newly added directory
4. content gets added to the new README based on the updated `catalog.json` file
  4.1. frontmatter gets automatically generated
  4.2. `<Schema/>` component gets automatically added

## Acceptance

* [x] a script that for each new `table-schema` added to the `catalog.json`
  * [x] creates new directory 
  * [x] adds README.md 
  * [x] generates frontmatter
* [x] the contributor only needs to edit `catalog.json` and send PR
* [x] the maintainer only needs to review and merge the PR and run a script

## Tasks

* [x] brainstorm on best, easiest and shortest pipeline / adding-a-new-table-schema-process.
--> see description above
* [x] write a script in node.js that does the job
* [x] test it 
* [x] push the changes

**Comment by monikappv** [comment]
FIXED.

the script is called `new-schemas.js` and is in https://github.com/frictionlessdata/schema-catalog/tree/master/site/catalog
