### ISSUE TITLE
Analyse protocol buffers and map types against table schema

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/project#517]
Protocol buffers is widely used and high quality low level (syntactical) data exchange format from Google.

## Acceptance

* [ ] Summary of protocol buffers
* [ ] Table of protocol buffer types
* [ ] Map of those types to table schema
* [ ] Any relevant code snippets
* [ ] Published somewhere

## Tasks

* [ ] Read up on https://developers.google.com/protocol-buffers

## Analysis

---

Please preserve this line to notify @lwinfree (lead of this repository)
