### ISSUE TITLE
Create Metadata Profiles for specific domains e.g. Grant Funding, Art Collections, Trees etc

### ISSUE THREAD

**Issue by pwalsh** [frictionlessdata/project#549]
# Description

Depends on frictionlessdata/project#475 

After frictionlessdata/project#475 we have a template of text, and supporting files for a simple demonstrator of a profile / data standard that describes a specific domain. Follow this pattern for the other suggested profiles.

# Tasks

- [ ] Grant funding
  - http://standard.threesixtygiving.org/en/latest/ | http://standard.threesixtygiving.org/en/latest/reference/
  - [ ] Sample data
  - [ ] Sample Table Schema
    - [ ] Sample Tabular Data Package?
  - [ ] Sample JSON Schema
  - [ ] Sample Python snippet
- [ ] Art collections
  - Copy and adjust as required from https://github.com/cmoa/collection
  - [ ] Sample data
  - [ ] Sample Table Schema
    - [ ] Sample Tabular Data Package?
  - [ ] Sample JSON Schema
  - [ ] Sample Python snippet
- [ ] Trees
  - http://standards.opencouncildata.org/#/trees
  - [ ] Sample data
  - [ ] Sample Table Schema
    - [ ] Sample Tabular Data Package?
  - [ ] Sample JSON Schema
  - [ ] Sample Python snippet
- [ ] Street furniture
  - http://standards.opencouncildata.org/#/street-furniture
  - [ ] Sample data
  - [ ] Sample Table Schema
    - [ ] Sample Tabular Data Package?
  - [ ] Sample JSON Schema
  - [ ] Sample Python snippet

**Comment by lwinfree** [comment]
Closing because this is out-of-scope for the current technical roadmap.
