### ISSUE TITLE
[profiles] Clinical trials profile

### ISSUE THREAD

**Issue by pwalsh** [frictionlessdata/project#550]
# Tasks

- [ ] Produce a sample dataset of around 100 records, as per the relevant Table Schema descriptor (or, update the descriptor to match the data).
- [ ] Create a JSON Schema that validates the Tabular Data Package under a custom profile name
  - Examples:
    - https://github.com/frictionlessdata/specs/blob/master/sources/dictionary/package.yml#L52
    - https://github.com/frictionlessdata/specs/blob/master/sources/dictionary/resource.yml#L70
- [ ] Simple example of use with Python

**Comment by lwinfree** [comment]
Closing since this is out-of-scope for the technical roadmap.
